### ISSUE TITLE
Client doesn't properly handle Bad Request responses

### ISSUE THREAD

**Issue by MuffinMan10110** [recurly/recurly-client-net#106]
For example, attempting to terminate a subscription that is expired will result in the following response:

    HTTP/1.1 400 Bad Request
    <?xml version="1.0" encoding="UTF-8"?>
    <error>
      <symbol>invalid_transition</symbol>
      <description>A expired subscription can't transition to expired</description>
    </error>

Client.cs doesn't appear to have a switch condition for this HTTP status so what ends up getting propagated back to the client is `The remote server returned an error: (400) Bad Request.` It really should be returning a RecurlyException with the error above inside the `Errors` array. Additionally since there's only one error we can set the Message property to the description in the error.

https://github.com/recurly/recurly-client-net/blob/master/Library/Client.cs#L169

**Comment by bhelx** [comment]
I think i have taken care of this here: https://github.com/recurly/recurly-client-net/pull/164

It's in the 1.4.0 release: https://github.com/recurly/recurly-client-net/releases/tag/1.4.0
