### ISSUE TITLE
Can we refactor Subscription.UpdateNotes method?

### ISSUE THREAD

**Issue by 1TheMuffinMan** [recurly/recurly-client-net#107]
The update notes method https://github.com/recurly/recurly-client-net/blob/master/Library/Subscription.cs#L398 currently takes a dictionary as an argument. 

There's a couple reasons this is a bad idea:
1. No one knows what keys are excepted
2. The way `UpdateNotes` handles the dictionary you must provide all 3 notes even if you want to just update one.

I suggest we change the signature to:
`public void UpdateNotes(string termsConditions, string customerNotes, string vatChargeNotes)` this way you can simply pass `null` to any ones you don't want to update.

**Comment by bhelx** [comment]
@MuffinMan10110 these are good points. I'm down to change the signature as long as we keep the dictionary signature available for backwards compatibility. I can update the examples in the docs to use the new signature to encourage use.

**Comment by MuffinMan10110** [comment]
@bhelx Thanks for following up! I will move forward with this soon.

**Comment by 1TheMuffinMan** [comment]
I looked into this further and I don't think it's worth the effort. 

- The first concern is to add an overload that takes named arguments so that you don't have to look up the documentation for the keys
- This way it would be possible to only specify one note to update and pass null to the others or any empty string to actually set the note to null or empty.
- The API endpoint treats null, empty string or whitespace all as null

While we can find a way around all of these I think it's more work than is practical for an endpoint that is probably very low use.
