### ISSUE TITLE
Get Tests and CI running

### ISSUE THREAD

**Issue by bhelx** [recurly/recurly-client-net#110]
In the rest of our libraries, we use travis to run the tests and don't merge anything where the tests do not pass. We should be doing the same thing in this library. In order to do this, we should add a travis config and fix the tests (or remove the ones that aren't working). Once we have travis protecting PRs we can get more serious about adding tests for each change.

@MuffinMan10110 let me know if you have any input on this. I plan to get this done in the next few weeks.

**Comment by MuffinMan10110** [comment]
@bhelx Your idea sounds good to me. 

Note that a bit of work is going to be required to get the tests in a place to be run in an automated environment.

1. I know there are a handful of tests that are either deprecated or are impossible to run in the current state of the Recurly account associated with the library.
2. Last time I checked some tests encountered one or more race conditions and failed when being run with all of the others, retrying them one at a time was successful.

**Comment by bhelx** [comment]
@MuffinMan10110 I noticed the same.

My plan was to just delete (or maybe comment out) any tests that are causing problems. I'll attempt to fix them but if I can't find a good fix or I don't understand them, they will be removed. I'm definitely more concerned about getting `some` tests running at all than having `all` of them running. We can work on incrementally improving them from that point forward. We can just draw a line in the sand at that point. It's not ideal but I think it's the best way to get started on making things better.

**Comment by MuffinMan10110** [comment]
@bhelx That makes sense about getting some tests running.

**Comment by bhelx** [comment]
Closing with https://github.com/recurly/recurly-client-net/pull/113

I think some more improvements could be made in the future but we'll open up specific tickets for that

**Comment by bhelx** [comment]
Just a note, if we want to put integration tests into travis in the future we'll need to find out what is making them so inconsistent as well as slow.
