### ISSUE TITLE
Upcoming multiple coupons

### ISSUE THREAD

**Issue by MuffinMan10110** [recurly/recurly-client-net#112]
It appears that multiple coupons per account are in beta according to this page: https://docs.recurly.com/coupons-beta

Is there currently anyone assigned to implementing these changes once the API is finalized? If not, I'm thinking a new branch could be made immediately and work started via pull request. A separate beta account could also be setup and linked to the branch to test with. Once the coupon changes are out of beta we can make any file changes if necessary and merge into master branch. By starting now we could have an update out soon after the coupon changes go into production.

I'm open to taking this on if you guys don't have someone working on it already.

**Comment by bhelx** [comment]
The latest version should support most of these changes. The API changes are finalized on our end.

I think most of the changes were made here: https://github.com/recurly/recurly-client-net/pull/102

I'm also working on these two others for editing and restoring coupons and also supporting the new `bulk` coupons.

https://github.com/recurly/recurly-client-net/pull/109
https://github.com/recurly/recurly-client-net/pull/108

I think these should cover most of it. If you see anything missing please point it out. And if you want to get these features enabled for your site let me know.

**Comment by MuffinMan10110** [comment]
Awesome, I didn't realize work had already been done for this. I will definitely reach out if we need this functionality before release.

Thanks.

**Comment by bhelx** [comment]
Thanks for looking out!
