### ISSUE TITLE
Add Webhooks support

### ISSUE THREAD

**Issue by ianschmitz** [recurly/recurly-client-net#117]
Would love to see some basic Webhooks support in the .NET client. Currently I have to manually deserialize the webhook requests.

**Comment by MuffinMan10110** [comment]
@ianschmitz What framework are you using (so we can get some more context)?

In ASP.NET MVC and Web API if you create a model the framework will automatically populate it for you. Depending on what you're using I might be able to provide some code.

**Comment by ianschmitz** [comment]
We are using ASP.NET Web API.

**Comment by MuffinMan10110** [comment]
I see where you might be having an issue - Recurly wants to send all Webhook notifications to one single URL which makes it a bit of a chore.

The simplest way I can think of doing it is loading it up in an `XDocument` writing a switch block on the root name and then serializing it into a specific class.

I think this is a good request and I'd be willing to add it to the client library in the next few weeks. In the meantime here is a quick and dirty Fiddle demonstrating how to do it with LINQ to XML. Note that it lacks proper error checking and could probably be simplified.

https://dotnetfiddle.net/CO7INv

**Comment by ianschmitz** [comment]
Thanks for the sample @MuffinMan10110 !

**Comment by bhelx** [comment]
Thanks @MuffinMan10110 !

**Comment by MuffinMan10110** [comment]
I believe this is resolved with the code sample I provided. 

@bhelx Can we close this?

**Comment by bhelx** [comment]
Certainly
