### ISSUE TITLE
account.Create() when no BillingInfo.

### ISSUE THREAD

**Issue by dylanjmcdonald** [recurly/recurly-client-net#118]
Getting a "Object reference not set to an instance of an object." error when trying to create an account. Turns out BillingInfo cannot be null. Billing info requires account to instantiate.

What should happen first?

**Comment by MuffinMan10110** [comment]
@dylanjmcdonald Can you provide some sample code of how you're creating the account object? You should be able to create an account without billing info.

**Comment by dylanjmcdonald** [comment]
https://gist.github.com/dylanjmcdonald/bd1a454bd932efbe01c1

user.UserId is a Guid. user & userSettings are not null. Locals shows values when debugging.

**Comment by MuffinMan10110** [comment]
Thanks for the additional information - null values was my next question :+1: 

It's interesting that you're getting an object reference error - if billing info is null it won't write to the request xml and the reader for the response doesn't read billing info. What version of the library are you using? Regardless, I'm curious to find out what's causing the error, if the request was invalid you should be getting a nice RecurlyException.

**Comment by dylanjmcdonald** [comment]
1.2.4, latest from NuGet Package Manager

**Comment by dylanjmcdonald** [comment]
Perhaps a dumb question, but does creating accounts work in sandbox mode?

**Comment by MuffinMan10110** [comment]
I just ran the create account unit test in the latest version and it seems to be working.

Here's the next steps I'd try in order to isolate the problem area
- Try to create an account with a static account code
- Inspect/provide the HTTP request/response using something such as Fiddler. 

I would like to determine if the API is sending back an error and it's being propagated back through the code, or if the request/response is successful and the code is handling it wrong.

**Comment by MuffinMan10110** [comment]
@dylanjmcdonald Yes, everything works in Sandbox mode. You'll just need to setup the Recurly section in your app/web.config which contains the subdomain and api key.

**Comment by dylanjmcdonald** [comment]
![Forehead slap](http://i.imgur.com/KrILoD4.jpg)

I had my section added to my app.config file in the project that references recurly-client-net and not in my web.config. Thanks for your help @MuffinMan10110!

Please close issue.

**Comment by MuffinMan10110** [comment]
:+1:  Glad I could help.
