### ISSUE TITLE
RecurlyServerUri is incorrect in NuGet package 1.2.5

### ISSUE THREAD

**Issue by ianschmitz** [recurly/recurly-client-net#122]
It looks like the version published to NuGet (1.2.5) has a Debug server url set which causes any client's using this package to get a WebException as follows:
```
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:3000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, WriteXmlDelegate writeXmlDelegate, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate reseponseDelegate)
```

I quickly decompiled the .dll from the NuGet package and looked in Recurly.Configuration.Settings and noticed: `protected const string RecurlyServerUri = "http://{0}.lvh.me:3000/v2{1}";`

I will revert back to 1.2.4 until i hear that the NuGet package has been fixed.

**Comment by MuffinMan10110** [comment]
@bhelx Only thing I can think of is the Nuget package got created from a local version that doesn't completely match what's in source control. 

The source code in the repository doesn't contain the value that Ian reported. It's `protected const string RecurlyServerUri = "https://{0}.recurly.com/v2{1}";`

I won't be able to confirm until later tonight.

**Comment by ianschmitz** [comment]
@MuffinMan10110 exactly my thoughts. I checked the source control first thing, but after seeing the requests captured by Fiddler i took a closer look in the .dll

**Comment by bhelx** [comment]
Appears to be an accident. Publishing a new version.

**Comment by bhelx** [comment]
@ianschmitz @MuffinMan10110 can you verify v1.2.6 ?

**Comment by MuffinMan10110** [comment]
@bhelx At the office we've designated a random object as a symbol of breaking the build, you have to keep it on your desk until someone else breaks the build. I might mail it to you :eyes:

**Comment by bhelx** [comment]
@MuffinMan10110 :/

Yes I need a dunce hat of some sort. Our release process is quite manual and I think this was human error (It wasn't in the source code but I moved over some old .dll to the nuget release folder). Will need to investigate doing this in a more automated way to avoid these kinds of mistakes.

In the mean time feel free to make of me on twitter or elsewhere.

**Comment by ianschmitz** [comment]
@bhelx 1.2.6 looks good!

**Comment by MuffinMan10110** [comment]
@bhelx The Nuget.exe can be command line driven so it would be very easy to create a script that downloads the latest version of master into a temp folder and then creates and publishes the package. To finish it off you could launch a browser tab to Nuget.org to double confirm the package is up there.

If you need help on this give me a shout.

**Comment by bhelx** [comment]
@ianschmitz phew. Thanks for reporting so quickly! Going to update the release notes now.

@MuffinMan10110 Definitely creating a script before the next release. This is too flaky of a process.

**Comment by MuffinMan10110** [comment]
@bhelx A quick google on "nuget from github repo" yielded this - http://weblogs.asp.net/bsimser/automatically-publishing-nuget-packages-from-github

**Comment by bhelx** [comment]
Thanks @MuffinMan10110 !
