### ISSUE TITLE
InvoicePreview removed when Previewing a Subscription

### ISSUE THREAD

**Issue by joelscrypt** [recurly/recurly-client-net#131]
So, the following code in Subscription.cs was removed:

                        //only parse the invoice xml if it's not just a link
                        if (string.IsNullOrEmpty(href))
                            InvoicePreview = new Invoice(reader);

and replaced with:

                        if (null != href)
                            _invoiceNumber = Uri.UnescapeDataString(href.Substring(href.LastIndexOf("/") + 1));

Now the InvoicePreview is no longer set and the Invoice is null as well.  Is this an issue in-progress that will be fixed or is there another way to view the Invoice?

**Comment by MuffinMan10110** [comment]
It looks like an if/else should have been used here. The original parses the Invoice XML if it exists and if the element is just a link to the invoice the new version sets the invoice number.

Also, to nitpick, any changes to the library should follow existing coding standards. `null != href` should be `href != null`.

**Comment by joelscrypt** [comment]
Agreed.

**Comment by MuffinMan10110** [comment]
@joelscrypt If you'd like to help fix this it would be much appreciated, otherwise I might be able to get to it this weekend.

@bhelx has the continuous integration setup pretty smoothly so he could probably have the Nuget package updated pretty quickly.

**Comment by joelscrypt** [comment]
Sure, pull request made.

**Comment by joelscrypt** [comment]
Hmm, the CI build failed getting mono...

**Comment by bhelx** [comment]
@joelscrypt thanks for reporting! Checking it out now

**Comment by joelscrypt** [comment]
@bhelx Sure, no problem.

**Comment by bhelx** [comment]
Fix for this went out in https://github.com/recurly/recurly-client-net/releases/tag/1.3.1
