### ISSUE TITLE
No InvoicePreview returned when calling PreviewChange() on a Future subscription

### ISSUE THREAD

**Issue by NaughtyMC** [recurly/recurly-client-net#135]
If I have a subscription that is set to start at some point in the future, calling PreviewChange() on that subscription (to preview a different number of add-ons, for example) returns a XML package that does not have an "invoice" node.

Is this the correct way to preview a change on a future subscription or am I missing something here?

**Comment by bhelx** [comment]
@NaughtyMC I think I would expect to see an invoice. Any way you could show me some code? It may be that the preview method is not sending over the addon changes.

**Comment by NaughtyMC** [comment]
@bhelx We found a work-around for this. By inserting a subscription for the current period, with an update at renewal, the PreviewChange method works correctly.

Thanks for your attention.

**Comment by bhelx** [comment]
@NaughtyMC thanks for reporting back. If you have the change, could you give us some more information for people who may later find this issue?

**Comment by NaughtyMC** [comment]
Okay @bhelx, here goes.

Background: there are two methods that are used for previewing subscriptions: Preview() and PreviewChange(). If the account you are previewing for already has a subscription of the preview type, you must use PreviewChange(). Otherwise, use Preview().

However, when you add a subscription of a given plan (let's call it 1A) with a start date in the future, a problem arises. You cannot use Preview() to preview plan 1A, as the API will return the error message "you already have a subscription to this plan" (same error message you would get if you tried to use Preview() and had a currently active subscription to plan 1A). Therefore, you have to use PreviewChange().

When the account's subscription is set to begin in the future, however, PreviewChange does not return the XML information that is usually parsed into the Invoice object. Simply put, it makes it impossible to preview a 1A subscription when you have a 1A subscription with a future start date.

Our work-around: when we want a subscription to start on the first renewal, we insert a subscription with no cost for the current period and immediately update it with a renewal type of Renewal. This allows use to use the PreviewChange() method correctly (necessary in the case that the customer wants to alter his subscription before the subscription is actually set to start).
