### ISSUE TITLE
Discount coupon not being applied when form is submitted

### ISSUE THREAD

**Issue by kylelengling** [recurly/recurly-client-net#137]
Have a form setup using RecurlyJS to create a subscription. I've created an input with the data-recurly="coupon" field to allow users to input a discount code. Using recurly.pricing I can see that the discount exists when entering a valid code, however when I submit the form and the subscription is created, the coupon is not used and the full price is charged. I think I need to add something to the subscription creation action in the API wrapper, but I can only find documentation on how to redeem a specific coupon, not redeem whatever coupon code the user has entered. 

Thanks!

**Comment by csmb** [comment]
Hey there @kylelengling, make sure that you're passing in `coupon_code` in your API call. Check out this line in the client: https://github.com/recurly/recurly-client-net/blob/master/Library/Subscription.cs#L703

If you're setting `coupon_code` in your request and it's not being respected, let me know!

**Comment by bhelx** [comment]
One of the constructors has a coupon-code param:

https://github.com/recurly/recurly-client-net/blob/master/Library/Subscription.cs#L298

**Comment by kylelengling** [comment]
@csmb Thanks for the reply! Forgive me if this dumb question, but where within my Subscription service file would I pass in the coupon_code? Currently it's calling a public bool to get the UserBillingInfo and token information submitted by the RecurlyJS form and then using that billing information to change/create the subscription. 

Thanks for your help!
```
 public bool AddUserBillingInfo(Guid userId, string tokenId)
        {
            try
            {
                var account = Accounts.Get(userId.ToString());
                account.BillingInfo = new BillingInfo(account)
                {
                    TokenId = tokenId
                };
                account.BillingInfo.Update();
                return true;
            }
            catch
            {
                // Use (ValidationException ex)
                return false;
            }
        }

        public void ChangeUserSubscription(Guid userId, string subscriptionName)
        {
            try
            {
                var account = Accounts.Get(userId.ToString());
                var plan = Plans.List().Single(x => x.Name == subscriptionName);
                var currency = "USD";
                var subscription = new Subscription(account, plan, currency);

                // Terminate any current subscriptions before we subscribe user
                // to new subscription.
                account.GetSubscriptions()
                    .Where(x => x.State == Subscription.SubscriptionState.Active)
                    .ToList()
                    .ForEach(x => x.Terminate(Subscription.RefundType.Partial));

                subscription.Create();
            }
            catch
            {
                // Use (NotFoundException ex)
                CreateUserAccount(userId);
            }
        }
```

**Comment by kylelengling** [comment]
I'm now trying to use this 

```
  private Coupon _coupon;
        private string _couponCode;

        private Coupon[] _coupons;
        private string[] _couponCodes;

        /// <summary>
        /// Optional coupon for the subscription
        /// </summary>
        public Coupon Coupon
        {
            get { return _coupon ?? (_coupon = Recurly.Coupons.Get(_couponCode)); }
            set
            {
                _coupon = value;
                _couponCode = value.CouponCode;
            }
        }           

        public void ChangeUserSubscription(Guid userId, string subscriptionName)
        {
            try
            {
                var account = Accounts.Get(userId.ToString());
                var plan = Plans.List().Single(x => x.Name == subscriptionName);
                var currency = "USD";
                var subscription = new Subscription(account, plan, currency, _couponCode);




                // Terminate any current subscriptions before we subscribe user
                // to new subscription.
                account.GetSubscriptions()
                    .Where(x => x.State == Subscription.SubscriptionState.Active)
                    .ToList()
                    .ForEach(x => x.Terminate(Subscription.RefundType.Partial));

                subscription.Create();
            }
            catch
            {
                // Use (NotFoundException ex)
                CreateUserAccount(userId);
            }
        }
```

but it still won't apply the code the subscription

**Comment by csmb** [comment]
It's possible that the coupon code doesn't exist in Recurly yet, or that the coupon has specific plans it applies to, and this isn't one of those plans. I'll take a look and try reproducing what you're seeing

**Comment by kylelengling** [comment]
@csmb I've got multiple coupons created, some that apply on the subscription level and some that non-subscription specific. Thanks for taking a look!

**Comment by 1TheMuffinMan** [comment]
@kylelengling Hi, I'm going through old open issues to see if I can resolve them. Before closing this I was wondering if you resolved this or still need assistance? Thanks!

**Comment by 1TheMuffinMan** [comment]
@kylelengling @csmb If you experience any further issues related to this or have more feedback to add please let me know. In the meantime I will close this.
