### ISSUE TITLE
C# API Not Handling Coupons In Subscriptions

### ISSUE THREAD

**Issue by djovanovi** [recurly/recurly-client-net#138]
I wanted to highlight a problem we are continuing to have referencing subscriptions with coupons using your C# API.

When I run an API call on one of our existing (test) subscriptions using:

var subscription = Recurly.Subscriptions.Get(newSubscriptionDetails.subscription.uuid);

where uuid references a valid subscription, the XML payload that is returned shows an error/exception in the coupon fields as in Pic1 (see highlights in blue). 

![pic1](https://cloud.githubusercontent.com/assets/8515814/12816203/af37bc1c-cb10-11e5-82c1-16dfecf727c9.jpg)

However, if I look at this account in the web console panel the subscription shows very clearly that a valid coupon is attached (see Pic2)

![pic2](https://cloud.githubusercontent.com/assets/8515814/12816220/c110b858-cb10-11e5-9010-d715077d003d.jpg)

 
Where this is causing me problems is when I try to serialize the subscription object into a Json I get an error related to the Coupon field .. 

Is this a known issue with a workaround or possible a bug in the C# API ? 

Follow-Up: I spoke with Charlie Gerrior and he indicated that the problem was an incomplete C# implementation of the latest subscription/coupon XML payload

**Comment by cgerrior** [comment]
@cbarton @bhelx Any chance either of you could take a look at this?

**Comment by bhelx** [comment]
@cgerrior Could you add any details you know about it?

**Comment by bhelx** [comment]
@djovanovi I'm able to reproduce the issue you are seeing above, but I think it's just an issue with how the debugger works. It seems when I pull up a subscription in the debugger it calls every method on the object and i think it's trying to improperly call Coupons.

You should be able to get redemptions by using the API as expected (using `GetRedemptions`):

```csharp
  var subscription = Recurly.Subscriptions.Get("352e52069aa207245b96a84331881f46");
  var redemptions = subscription.GetRedemptions();
```

![screen shot 2016-03-28 at 4 27 22 pm](https://cloud.githubusercontent.com/assets/185919/14093388/59a5eb9a-f502-11e5-9948-6e595615082e.png)

Please re-open if you think this answer didn't solve your problem. I'd be happy to help you get to the bottom of it.

**Comment by djovanovi** [comment]
Thanks Benjamin,
I will test soon and get back if I still see the issue outside of the
debugger.
Appreciate your help !
-DJ
