### ISSUE TITLE
Update Plan Addon - throw exception

### ISSUE THREAD

**Issue by zjazd** [recurly/recurly-client-net#140]
Example from https://dev.recurly.com/docs/update-an-add-on

var plan = Plans.Get("gold");
var addon = plan.GetAddOn("ipaddresses");
addon.UnitAmountInCents["USD"] = 200;
addon.Update();

throws exception beaceuse PlanCode is null, and there is no public method or property that set PlanCode (only internal constructor)

**Comment by bhelx** [comment]
@zjazd This appears to be a bug. I have a longer term fix in mind but for now I have this PR that should fix the problem:

https://github.com/recurly/recurly-client-net/pull/141

**Comment by bhelx** [comment]
Closed with https://github.com/recurly/recurly-client-net/pull/141
