### ISSUE TITLE
Change Update and Delete methods to use href

### ISSUE THREAD

**Issue by bhelx** [recurly/recurly-client-net#142]
All of the resources in our API have an `href` attribute that points back to the object. Here is an example of an AddOn:

``` xml
<add_on href="https://your-subdomain.recurly.com/v2/plans/gold/add_ons/ipaddresses">
 <!-- ...... -->
</add_on>
```

This is helpful because you can store it on the object and the object doesn't need to know how to build back up it's route to update or delete itself. Doing so requires inflexible and unnecessary logic and also it requires that the resource has to track all of it's parent resources and their identifiers. Here is an example in the `AddOn` model:

https://github.com/recurly/recurly-client-net/blob/master/Library/AddOn.cs#L67-L73

``` csharp
public void Update()
{
  Client.Instance.PerformRequest(Client.HttpRequestMethod.Put,
    UrlPrefix + Uri.EscapeUriString(PlanCode) + UrlPostfix + Uri.EscapeUriString(AddOnCode),
    WriteXml,
    ReadXml);
}
```

This object must now store and track it's url parts, the PlanCode, the AddOnCode, and the logic to build this all back up. This could be replaced with something like this:

``` csharp
public void Update()
{
  Client.Instance.PerformRequest(Client.HttpRequestMethod.Put, GetHref(), WriteXml, ReadXml);
}
```

Where `Href` would be read from the XML and stored as an instance variable.

This would prevent issues like this https://github.com/recurly/recurly-client-net/pull/141 as well as simplify the code.

\cc @csmb @MuffinMan10110 for comments

**Comment by csmb** [comment]
I'm a fan. It seems like a great way to reduce complexity around locating objects. :+1:

**Comment by MuffinMan10110** [comment]
What you propose sounds like a more logical way to go about it.

**Comment by bhelx** [comment]
Okay, I'm going to put this on my calendar for next sprint.

**Comment by aaron-suarez** [comment]
We're not going to implement the HREFs at this time for this library. Closing this and the related PR.
