### ISSUE TITLE
Remove examples.md?

### ISSUE THREAD

**Issue by bhelx** [recurly/recurly-client-net#146]
I think maybe we should remove the `examples.md` file. I can't say for sure whether they all work It hasn't been updated. We should direct people to find examples at the docs site where we can keep things up to date. It's either that or we go through every example and check that they still work then keep it up in two places.

https://github.com/recurly/recurly-client-net/blob/master/examples.md

Opinions?

\cc @csmb @MuffinMan10110

**Comment by csmb** [comment]
Good catch! I think we should take a look at what it offers, and perhaps verify/update example code on `dev.recurly.com` with what's in `examples.md`.

**Comment by MuffinMan10110** [comment]
The problem with keeping examples on github is that there's always two places to update. Directing people to the docs on the Recurly site sounds like a better option to me.

**Comment by bhelx** [comment]
@MuffinMan10110 I agree. Too hard to keep up with

@csmb I'm going to do that client lib example code audit soon!

**Comment by 1TheMuffinMan** [comment]
@bhelx Can I remove examples.md or should I replace it with links to the documention:

API docs
https://dev.recurly.com/

.NET client docs
https://dev.recurly.com/page/net
