### ISSUE TITLE
Injectable Recurly API keys

### ISSUE THREAD

**Issue by supoo** [recurly/recurly-client-net#148]
It would be great if we can modify the Recurly API keys at runtime.

We are using Azure cloud services and most of our configuration is set in Azure cloud service configuration files. For sensitive keys/secrets/passwords, we inject these values in as we do not want any of the information available through our git repository. With the current setup, the Recurly API keys are easily readible in Web.config/App.config. This is not ideal.

Thanks!

**Comment by MuffinMan10110** [comment]
@supoo Help me understand your situation a little better. Your App/Web.config in source control should only contain sandbox/dev credentials. As part of your CI process your config files are transformed with the sensitive passwords and then deployed to production servers.

**Comment by bhelx** [comment]
@supoo Are you managing keys for your customers who are also Recurly customers (making API requests on their behalf)? Or are you talking about managing your own keys?

**Comment by supoo** [comment]
Hello, 

@bhelx , I am talking about managing our own keys.

@MuffinMan10110, fair enough. We're looking into doing the transformation with Jenkins. In the meantime, I'm interesting in how one uses Reflection to change configuration at runtime. Can you point me in the right direction?

Thanks!

**Comment by MuffinMan10110** [comment]
@supoo This should get you started

```csharp
public void UpdateSettings()
{
    //get the client singleton instance
    var clientInfo = typeof(Client).GetProperty("Instance", BindingFlags.Static | BindingFlags.NonPublic);
    var client = (Client)clientInfo.GetValue(null);

    //get the settings singleton instance
    var settingsProp =
        typeof(Recurly.Configuration.Settings)
        .GetProperty("Instance", BindingFlags.Static | BindingFlags.Public);

    //update settings
    var settings = settingsProp.GetValue(null);

    typeof(Settings).GetProperty("ApiKey").SetValue(settings, "some api key");
    typeof(Settings).GetProperty("PrivateKey").SetValue(settings, "some private key");
    typeof(Settings).GetProperty("Subdomain").SetValue(settings, "some subdomain");
    typeof(Settings).GetProperty("PageSize").SetValue(settings, 10);

    //update client with revised settings
    var method = typeof(Client).GetMethod("ApplySettings", BindingFlags.Instance | BindingFlags.NonPublic);
    method.Invoke(client, new[] { settings });
}
```

**Comment by supoo** [comment]
@MuffinMan10110, this is great. Thank you!

**Comment by bhelx** [comment]
@MuffinMan10110 thanks for the help! I'm gonna close this issue.
