### ISSUE TITLE
Adjustments.Get returns uninitialized object

### ISSUE THREAD

**Issue by markhansonX** [recurly/recurly-client-net#149]
I am using version 1.3.1.
When I call this code (I don't see in you public Library that this code has changed):

```
    public class Adjustments
    {
        public static Adjustment Get(string uuid)
        {
            var adjustment = new Adjustment();
            Client.Instance.PerformRequest(Client.HttpRequestMethod.Get,
                "/adjustments/" + Uri.EscapeUriString(uuid),
                adjustment.WriteXml);
            return adjustment;
        }
    }

```

the returned object is not initialized. Also there is no check on the return code on the PerformRequest.  It seems this should use ReadXml instead?? and also check the return code like:

```
        public static Invoice Get(string invoiceNumberWithPrefix)
        {
            var invoice = new Invoice();
            
            var statusCode = Client.Instance.PerformRequest(Client.HttpRequestMethod.Get,
                Invoice.UrlPrefix + invoiceNumberWithPrefix,
                invoice.ReadXml);

            return statusCode == HttpStatusCode.NotFound ? null : invoice;
        }

```

**Comment by MuffinMan10110** [comment]
Thanks for reporting this. You are correct, the argument for the XMLDelegate in the Get method for Adjustments should be `ReadXml` not `WriteXml`. I just debugged the unit test for this and it's just checking to see if the `adjustment` object is null or not which it will never be null.

I will fix this.

**Comment by bhelx** [comment]
Thanks for reporting @markhansonX 

I'm reviewing @MuffinMan10110 PR tonight
