### ISSUE TITLE
BLOCKER wrong request are send on change subscription

### ISSUE THREAD

**Issue by karolsws2** [recurly/recurly-client-net#157]
``` csharp
var account = Accounts.Get(accountName);
var subs = account.GetSubscriptions(Subscription.SubscriptionState.All);
var s = subs[0];
var newPlan = Plans.Get(planCode);

s.Plan = newPlan;
s.ChangeSubscription(Subscription.ChangeTimeframe.Now);
```

This code should change subscription it does change subscription but charges for 0.

You have to set manualy new plan amount in cents, otherwise it result in corrupted  subscription in recurly.

you have to put this line before change subscription

``` csharp
s.UnitAmountInCents = newPlan.UnitAmountInCents["EUR"];
```

It is antyintuitive, it is against all tutorials and helps, where you should set UnitAmountInCents only if you want to override plan default price.

**Comment by bhelx** [comment]
It would be great to see the xml generated here. If you have it let me know. I will try to reproduce on my end.

**Comment by bhelx** [comment]
This is what I am seeing
<img width="619" alt="screen shot 2016-10-05 at 2 41 19 pm" src="https://cloud.githubusercontent.com/assets/185919/19128617/bd262796-8b09-11e6-94de-bf2072d76a89.png">

**Comment by 1TheMuffinMan** [comment]
@bhelx Should changing a subscriptions plan automatically set the subscriptions unit amount in cents to the new plans amount, or should the subscription keep using the existing unit amount in cents?

I can make this change and create a unit test for it.

**Comment by bhelx** [comment]
@1TheMuffinMan I think the problem here is that it shouldn't be sending off `unit_amount_in_cents` unless it was explicitly changed. I think if that is fixed then the server will do the right thing. I believe it takes on the new plans price but not 100% sure.

**Comment by bhelx** [comment]
This seems to be a legitimate bug. I don't think we should be sending changes across in this way. We should only be sending the fields that change. We may need to change the way people use `ChangeSubscription` and `PreviewChange`

**Comment by bhelx** [comment]
@1TheMuffinMan I'm going to take a crack at this tomorrow morning. Did you find anything out about it?

**Comment by 1TheMuffinMan** [comment]
@bhelx I have not had a chance to look into this one yet.

**Comment by bhelx** [comment]
It just appears that these fields are getting sent over even though they weren't changed.
