### ISSUE TITLE
No PaymentMethod property on the Transaction object

### ISSUE THREAD

**Issue by Pckmule** [recurly/recurly-client-net#158]
Version 2 of the Recurly API supports getting a transaction's payment method, but this library currently does not. 

https://dev.recurly.com/docs/transaction-object

**Comment by bhelx** [comment]
@Pckmule Sorry I've been quiet on this. I've been pretty busy and let this library get a little behind. I'll eventually get to it but it may be a week or two. I'd be happy to review any pull requests. If it's just adding a the payment_method field it should be pretty simple.

**Comment by Pckmule** [comment]
@bhelx Thanks for the update. If you could have it done in a week that would be awesome. If not, we'll just have to wait a little bit. :)

**Comment by csmb** [comment]
@Pckmule I've got a PR up that addresses this. I'll let ya know when it's merged and released.

**Comment by bhelx** [comment]
Thanks a bunch @csmb !

**Comment by Pckmule** [comment]
@csmb Thanks, that is great news!

**Comment by bhelx** [comment]
This is closed with https://github.com/recurly/recurly-client-net/pull/159

**Comment by Pckmule** [comment]
Great stuff, thanks.
