### ISSUE TITLE
Usage-based billing in .NET client

### ISSUE THREAD

**Issue by AnaCampoVe** [recurly/recurly-client-net#161]
Hi team!!!

We aim to integrate Recurly in a MVC solution. Our model is usage-based billing.

We have downloaded your .NET client and have seen that it doesn't offer any method to log usage. Support team has told us that this feature is in development and testing. When are you planning to release the new version? Till that moment, is there any way for us to log customer usage from our .NET application?

Thanks and regards,

Ana

**Comment by bhelx** [comment]
@AnaCampoVe Yes, this is in development. I'll post here with updates. Some time next week would be my optimistic ETA.

**Comment by bhelx** [comment]
@AnaCampoVe finally got around to working on this: https://github.com/recurly/recurly-client-net/pull/165

I'm shooting for the end of this week.

**Comment by AnaCampoVe** [comment]
Good to know!!!

WE would be grateful if you le tus know when the client is updated!!

Thanks!

Ana

**Comment by bhelx** [comment]
This has been released with https://github.com/recurly/recurly-client-net/releases/tag/1.4.0
