### ISSUE TITLE
InvoicePendingCharges and invoice notes

### ISSUE THREAD

**Issue by mms-** [recurly/recurly-client-net#166]
InvoicePendingCharges does not use the subscription configured customer notes, and account does not seem to have a configuration. No way to set invoice notes on the current implementation of InvoicePendingCharges. Also Recurly seemingly does not allow this to be changed once the invoice is created.

Is the Nuget going to be released any time soon (close to a year now)? Or is this library not really maintained by Recurly?

**Comment by bhelx** [comment]
> InvoicePendingCharges does not use the subscription configured customer notes, and account does not seem to have a configuration. No way to set invoice notes on the current implementation of InvoicePendingCharges.

It seems like this feature was added but not implemented in this library. Would be happy to take a PR or I can put it in my queue.

> Also Recurly seemingly does not allow this to be changed once the invoice is created.

Could you explain what you mean with an example? I don't think we support changing invoices after they are created. 

> Is the Nuget going to be released any time soon (close to a year now)? Or is this library not really maintained by Recurly?

This is definitely still being maintained but we haven't done a release in a while. I pushed out a big release yesterday. Sorry if that was the appearance.

**Comment by mms-** [comment]
Will definitely do a PR if I find time to implement InvoicePendingCharges.

Invoices in Recurly seem immutable for the most part, that is setting something like notes can only be done at create time, so InvoicePendingCharges seems to be the only way..

**Comment by 1TheMuffinMan** [comment]
@mms- I'm planning on working on this issue this week. At a glance I'm thinking about updating the `InvoicePendingCharges` and associated `PreviewInvoicePendingCharges` methods to take a nullable `Invoice` object that contains all of the notes you want to set. Using a nullable argument makes it possible to continue to use the existing method without specifying the invoice argument for backwards compatibility.

**Comment by bhelx** [comment]
The tests in the accompanying PR show how to use this feature: https://github.com/recurly/recurly-client-net/pull/222/files#diff-c616f4d3e04af1d194fca9525cd711daR74

**Comment by mms-** [comment]
Will try this out soon. Thanks.
