### ISSUE TITLE
UsageTimestamp won't let you post in the future.

### ISSUE THREAD

**Issue by BenjaminGibbs** [recurly/recurly-client-net#170]
So this may not be a library issue but when creating a new usage I get an error saying I can't post in the future.

While this seems an obvious thing to have, it causes the problems when the client/server time is not in sync'd to the second.

From what I can make out my dev machine is about 25 seconds out from the recurly servers, so while I could update my local clock it doesn't solve the problem if our production servers time gets slightly out of sync.

My current work around is to remove a few minutes from the timestamp but that is not ideal as the data is then inaccurate, so now I am looking at how I can delay the post to recurly so it doesn't get rejected for being a few seconds out.

It would be helpful to for the server to accept dates/times with room for error maybe 5 minutes in to the future for example. - Unless I am doing something wrong?

**Comment by bhelx** [comment]
Yes, this is something that the API enforces but I thought we were giving a little bit of leeway with it. Let me check the server side code.

**Comment by BenjaminGibbs** [comment]
Great to confirm how I am looking at this:
The XML I posted in #168 the usage time I was logging was `2016-09-21T02:39:33+00:00` which had had 5 minutes removed.

The created time was logged as `2016-09-21T02:44:09+00:00`

So if I added back the 5 minutes the time on the local machine was `2016-09-21T02:44:33+00:00` which is looking to be about 24 seconds ahead of the servers and that was getting rejected.

**Comment by bhelx** [comment]
That seems like a pretty big skew. I've verified that there is a service on our backend that is perhaps too zealously guarding this value. We are talking about what it would require to loosen that restriction and if there are any downsides. Will let you know what we come up with.

As an aside, whose clock seems to be off by how much? Could you check your server time against NIST http://www.time.gov/ ?

**Comment by BenjaminGibbs** [comment]
@bhelx our beta and production machines are almost inline with time.gov.uk its is our dev machines that drifted out - we would have no issues in theory when going live. It just seemed a bit over zealous ;)

**Comment by bhelx** [comment]
@BenjaminGibbs okay. Good to know!

One possible solution we were thinking is if you send across a nil `usage_timestamp`, it defaults to `now` on our server. Still discussing the pros and cons of this and will hopefully be able to get out something suitable for next week.

**Comment by BenjaminGibbs** [comment]
@bhelx That would be an awesome solution to be honest.

In fact it was what I tried to do the first time I wrote some code around usage - I assumed it would use the current date/time when I submitted it if I didn't explicitly state it.

**Comment by bhelx** [comment]
Okay, we decided that is the implementation we are going with. I'll let you know when it's live.

**Comment by bhelx** [comment]
@BenjaminGibbs We've pushed the implementation for the server side. I have a small patch to allow null `UsageTimestamp`s https://github.com/recurly/recurly-client-net/pull/175

If it looks good to you, I'll push a patch change to Nuget

**Comment by BenjaminGibbs** [comment]
It looks good to me.

**Comment by bhelx** [comment]
@BenjaminGibbs I went ahead and published this alone as `1.4.2` https://github.com/recurly/recurly-client-net/releases/tag/1.4.2

**Comment by bhelx** [comment]
Closed with: https://github.com/recurly/recurly-client-net/issues/175
In release: https://github.com/recurly/recurly-client-net/releases/tag/1.4.2
