### ISSUE TITLE
Send BillingInfo Company via recurly js

### ISSUE THREAD

**Issue by AnaCampoVe** [recurly/recurly-client-net#172]
Hi Team!!!

We are trying to send Recurly our customers Billing Info via recurly js. To do that, we include data-recurly attribute in HTML fields and update the data with the token that is generated. It works ok for all the fields except for Company property. Isn't there any data-recurly="company" attribute that recurly.js can understand?

We have also tried to update Company property in Billing Info setting the value in .NET and we see that the value is not updated after executing BillingInfoUpdate method.

Where can be the problem? Isn't this implemented in the .NET client?

**Comment by csmb** [comment]
Hi @AnaCampoVe. There isn't a `company` attribute on billing info, however there is one on the `account` model. 

Here are the docs about Recurly JS, which outline the attributes you can send over when tokenizing a card: https://dev.recurly.com/docs/recurlyjs

Here's an example, showing how to create an account with a `company`:
``` C#
var account = new Account("1")
{
  Email = "verena@example.com",
  FirstName = "Verena",
  LastName = "Example"
  CompanyName = "Recurly"
};
account.Create();
```

Hope that helps out!

**Comment by AnaCampoVe** [comment]
Thanks for the quick reply!

Apart from the CompanyName attribute in Account, .NET client does have a Company attribute in the BillingInfo class. What does it stand for?

Regards,

Ana

**Comment by bhelx** [comment]
@AnaCampoVe It appears to be a mistake. I traced it back to a commit from 2012 https://github.com/recurly/recurly-client-net/commit/4a29c6619d9503beb8cbd0259d830ab474b1aa71 . I'm not sure how it happened. It may be that it was moved over to the account and never removed on the billing info. We'll remove it for the next release. Thanks for pointing it out!

**Comment by bhelx** [comment]
@AnaCampoVe Turns out I was wrong. You can in fact set this but the field wasn't described in the documentation. If you were creating a billing info with a token, it might look something like this:

```csharp
var account = Accounts.Get("1");
var info = new BillingInfo(account);
info.TokenId = "TOKEN_ID";
info.Comany = "My Company";
info.Create();
```

**Comment by bhelx** [comment]
I'm going to close this for now, sorry about the confusion. Let me know if you need help getting it to work for you.

**Comment by AnaCampoVe** [comment]
Sorry for bothering you again... When I opened this issue I already knew that the Company property could be set through the .NET client. The problem is that although I set the property, the fact is that the Company value is not properly updated in Recurly.

Thanks!

**Comment by bhelx** [comment]
@AnaCampoVe it's not being set via the .net client? or via recurly.js ?

**Comment by bhelx** [comment]
@AnaCampoVe sorry, just updating for anyone who finds the issue.
