### ISSUE TITLE
Zip Code validation

### ISSUE THREAD

**Issue by AnaCampoVe** [recurly/recurly-client-net#173]
Hi team!!!!

We are working on some forms to send the Billing Info to Recurly after they are filled in. Is there any way to perform ZipCode validation before Updating BillingInfo? 

Thanks,

Ana

**Comment by bhelx** [comment]
@AnaCampoVe When submitting the request for a token, the zip code should be getting validated. Is it not?

**Comment by AnaCampoVe** [comment]
Sure!!! I knew that!!! But my question is if I can validate the zip code before submitting all the information to Recurly. Thanks!

**Comment by bhelx** [comment]
@AnaCampoVe I suppose you could but you would have to add that logic yourself. It's probably a better idea to let that happen server side (on our side). You don't want to over zealously validate too much information. At the end of the transaction, the payment network will tell you whether or not the information is valid.

**Comment by AnaCampoVe** [comment]
Ok, I just wanted to know if there was any method which had the logic implemented... Thanks for the info!

**Comment by bhelx** [comment]
@AnaCampoVe Sure thing. Let us know if you have more questions.
