### ISSUE TITLE
How do I get off this notification stream? 

### ISSUE THREAD

**Issue by tfulton** [recurly/recurly-client-net#184]
Worked for Recurly a few months back.  Can someone instruct me on how to get off of these dang notifications?

**Comment by bhelx** [comment]
<img width="441" alt="screen shot 2016-10-27 at 10 57 25 pm" src="https://cloud.githubusercontent.com/assets/185919/19794519/77cb190e-9c98-11e6-8e58-4407fd9b8a72.png">

Click this button, choose `Ignoring`
