### ISSUE TITLE
Get subscription addon usage

### ISSUE THREAD

**Issue by annguyen209** [recurly/recurly-client-net#187]
Hi. 
There is no implement for getting subscription addon usage. Is this missed currently or it is somewhere I don't know.

Thanks in advance.
An.

**Comment by bhelx** [comment]
@annguyen209 Sorry, seems like that list class was missing. This branch should fix this for you: https://github.com/recurly/recurly-client-net/pull/188

**Comment by bhelx** [comment]
@annguyen209 let me know if it resolves this for you and i can get it merged and released

**Comment by annguyen209** [comment]
@bhelx It's worked. Thank you.

**Comment by bhelx** [comment]
@annguyen209 great, it will go into the next release
