### ISSUE TITLE
No way to get a human-readable error message

### ISSUE THREAD

**Issue by igor-shevchenko** [recurly/recurly-client-net#197]
From [documentation](https://dev.recurly.com/page/transaction-errors), it seems that there's a customer message in the error transaction response:

```
<?xml version="1.0" encoding="UTF-8"?>
<errors>
  <transaction_error>
    <error_code>fraud_security_code</error_code>
    <error_category>fraud</error_category>
    <merchant_message>The payment gateway declined the transaction because the security code (CVV) did not match.</merchant_message>
    <customer_message>The security code you entered does not match. Please update the CVV and try again.</customer_message>
    <gateway_error_code>301</gateway_error_code>
  </transaction_error>
  <error field="transaction.account.billing_info.verification_value" symbol="declined_bad">did not match</error>
  ...
</errors>
```

We can use that message to display an error to user. But I can't find a way to get it using the library since `ValidationException` contains only a list of [`Error`s](https://github.com/recurly/recurly-client-net/blob/master/Library/Error.cs). Is it possible?

**Comment by MuffinMan10110** [comment]
@igor-shevchenko What's the HTTP status code you receive? The Client.cs handles a variety of status codes so I'm trying to track down where this particular one would be handled.

**Comment by bhelx** [comment]
@igor-shevchenko I can't seem to find any code that parses the `transaction_error` which would be a big oversight on our part. I'll dig into the code and link back with a PR if we need one.

**Comment by igor-shevchenko** [comment]
@MuffinMan10110 It's 422.

As I've found out, the inner content of the `<error></error>`  element (which we can access via `Error.Message` property) is human-readable most of the time. But sometimes this message is not very useful.

For example, the [test card number](https://docs.recurly.com/docs/test) `4000-0000-0000-0051` returns message `"is not valid"`, and `4000-0000-0000-0101` returns `"did not match"`. In this cases I prefer to be able to read `transaction_error`.

**Comment by MuffinMan10110** [comment]
@igor-shevchenko I'm sure that we can update the library to handle `transaction_error` soon.

As far as the examples you gave for `did not match` and etc those would need to be handled in the API itself and would be a larger undertaking and introduce more risk than updating the .NET client library. I think for now your best bet is to map those internally to a better message.

Perhaps @bhelx can comment on the feasibility of coming up with a solid list of error messages that the Recurly API server returns and identify if any of the endpoints need to be updated to return an error format consistent with the others, I.E. more descriptive than `did not match`.

**Comment by igor-shevchenko** [comment]
@MuffinMan10110 thanks!

> I think for now your best bet is to map those internally to a better message.

Yes, that's what I do for now. I can't be absolutely sure these are the only cases though. 

There's a [list of errors](https://dev.recurly.com/page/transaction-errors), but it contains only values of `<transaction_error>` without mapping to `<error>`.

**Comment by bhelx** [comment]
Resolved with: https://github.com/recurly/recurly-client-net/pull/200

There is an example of using the `TransactionError` in the PR description there. Please reopen if this is still a problem.
