### ISSUE TITLE
Exception creating BillingInfo with AmazonBillingAgreementId

### ISSUE THREAD

**Issue by SuperStromboli** [recurly/recurly-client-net#208]
I followed the Recurly docs for creating a BillingInfo using a third party token.  When I submit the Amazon payment using recurly.js I get an exception when attempting to (Update|Create) the BillingInfo object.  I've had this issue with client version 1.3.1.  Currently on 1.4.7 though and using our Recurly sandbox URL for testing.  Account used for Pay With Amazon is also a sandbox account.

`The information being saved is not valid.`

`at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, WriteXmlDelegate writeXmlDelegate, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate reseponseDelegate) in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\Client.cs:line 222
at Recurly.BillingInfo.Update() in C:\Users\ben\Documents\GitHubVisualStudio\recurly-client-net\Library\BillingInfo.cs:line 171
at APIService.APIBusinessLogic.subscribeRecurly(SubscribeData data) in C:\Users\eleva\Projects\Mathway3\APIService\APIBusinessLogic.cs:line 2412`

Not too sure if I should be seeing @bhelx's environment path in there either...

Pertinent code:
```
Recurly.BillingInfo billinginfo = new Recurly.BillingInfo(account);
if (tokenid.Contains("-"))
{
    // Amazon
    billinginfo.FirstName = "Test";
    billinginfo.LastName = "Test";
    billinginfo.AmazonBillingAgreementId = tokenid; // "C01-7531009-8000867"
}
else
{
    // CC
    billinginfo.TokenId = tokenid;
}
billinginfo.Create();
```

Let me know if you guys need more info. Thanks!

**Comment by bhelx** [comment]
Hey @SuperStromboli Could you try digging into the validation errors to see which fields are not valid and why? Try something like this:

```csharp
            try
            {
                Recurly.BillingInfo billinginfo = new Recurly.BillingInfo(account);
                if (tokenid.Contains("-"))
                {
                    // Amazon
                    billinginfo.FirstName = "Test";
                    billinginfo.LastName = "Test";
                    billinginfo.AmazonBillingAgreementId = tokenid; // "C01-7531009-8000867"
                }
                else
                {
                    // CC
                    billinginfo.TokenId = tokenid;
                }
                billinginfo.Create();
            } catch (ValidationException ex)
            {
                foreach (var err in ex.Errors)
                    Console.WriteLine(err.ToString());
            }
```

**Comment by bhelx** [comment]
As for my local paths being in the error message, I'm unsure why you are seeing this or what it means. Perhaps I am doing something wrong in the build process? Maybe you or @1TheMuffinMan have an idea why it does this.

**Comment by bhelx** [comment]
I think this may provide the answer: http://stackoverflow.com/questions/12281962/why-does-the-stack-trace-shows-my-development-files-path

**Comment by SuperStromboli** [comment]
Thanks for the tip on iterating through the validation errors.  I'll report back tomorrow.

**Comment by SuperStromboli** [comment]
Ok, output for that was fairly simple: `is required | Field: "billing_info.number" Code: "" Symbol: "required" Details: ""`

I don't see a member called _Number_.  Also available are: _AccountNumber_, _CreditCardNumber_, _PhoneNumber_, _RoutingNumber_, _VatNumber_.

Ideas?

**Comment by bhelx** [comment]
This library chose to map the `CreditCardNumber` property to the `number` field in the xml: https://github.com/recurly/recurly-client-net/blob/master/Library/BillingInfo.cs#L321 The errors always refer to the xml name. This should be one of the few diversions from the convention of naming the property the same as the xml element.

Now that I am looking at the XML, I don't think we are writing the `amazon_billing_agreement_id`, only reading it. Here is where we are doing it for Paypal for instance: https://github.com/recurly/recurly-client-net/blob/master/Library/BillingInfo.cs#L335 . That would explain why the validator would be expecting to see a credit card number (it defaults to treating the billing info as a credit card). You may be the first person using this feature in this library :)

I'll add a PR to write the amazon token right now.

**Comment by SuperStromboli** [comment]
I got that feeling!  Hah, thanks.

**Comment by bhelx** [comment]
@SuperStromboli Could you try out #209 and let me know if it resolves the issue?
