### ISSUE TITLE
Calling 'Plans.List()' will always throw a `NullReferenceException`

### ISSUE THREAD

**Issue by CodingGorilla** [recurly/recurly-client-net#229]
From Plans.cs:

```
public static RecurlyList<Plan> List(FilterCriteria filter)
{
     filter = filter.Equals(null) ? FilterCriteria.Instance : filter;
    return new PlanList(Plan.UrlPrefix + "?" + filter.ToNamedValueCollection().ToString());
}
```

`Plans.List()` is an overload that calls: `Plans.List((FilterCriteria)null);`.  This will always throw an NRE because you cannot call the `.Equals()` of a null object, so the statement: `filter.Equals(null)` is actually very silly because it can never actually succeed.

Personally I would replace this with:

```
filter = filter == null ? FilterCriteria.Instance ? filter;
```

But I suppose you could also do:

```
filter = ReferenceEquals(filter, null) ? FilterCriteria.Instance ? filter;
```

I'm not sure that one has a particular advantage over the other.  I can submit a pull request if you want, but for the time being in my code I just replaced the empty overload call with a call containing the `.Instance` value to work around this issue.

**Comment by 1TheMuffinMan** [comment]
Thanks for bringing this up.

I'm not sure why `filter.Equals(null)` was used instead of `filter == null`.

If you want to submit a pull request I will approve it.

**Comment by jakenuts** [comment]
I think this affects all the List() calls with FilterCriteria..

**Comment by CodingGorilla** [comment]
I apologize I did not check the tests, many of the tests always fail for me when I run the, but I assumed that had something to do with the attempt to actually communicate with Recurly and a lack of credentials or something on my part.

I can't see why this would have a negative effect, functionally there should be no difference between `filter.Equals(null)` and `filter == null`.

**Comment by bhelx** [comment]
@CodingGorilla @jakenuts It's because when we added the filters we delegate the old methods to the new with the filter parameter:

https://github.com/recurly/recurly-client-net/blob/master/Library/Account.cs#L550
https://github.com/recurly/recurly-client-net/blob/master/Library/Plan.cs#L395

I'll go fix all of them and make sure it's represented in the tests.

**Comment by CodingGorilla** [comment]
@bhelx I understand the relationship, but I don't understand what would cause a failure.  What is the functional difference that causes the error?

**Comment by bhelx** [comment]
I think this can be closed with #231 thanks to @jakenuts 
I will get a release out tomorrow.

**Comment by bhelx** [comment]
Sorry @CodingGorilla I think I still don't get what question you are asking. From my understanding, we were explicitly passing in `null` in the 0-arity methods. It seems to me that  the `Object#Equals(Object)` was not meant to do null checks but we were using it with the intention to do a null check. I'm not sure if there are other situations where it would function differently but all we want to do is check if it's null so i think `filter == null` is fine.

**Comment by CodingGorilla** [comment]
@bhelx I agree `filter == null` and `filter ?? statement` should have the same result (in fact I think the latter is just syntactic sugar for the former).  The original assertion (or at least what I _thought_ was the original assertion) was that my code change to use `filter == null` caused other unit tests to fail somewhere and I was puzzled as to why that would be the case.

But honestly, as long as it all works now, it's all good. :)

**Comment by bhelx** [comment]
@CodingGorilla okay good. Just wanted to make sure I was understanding and addressing your concerns. Thanks for being on top of it!
