### ISSUE TITLE
Account Balance call to the API is not available in the C# client

### ISSUE THREAD

**Issue by argystu** [recurly/recurly-client-net#233]
I was looking for a way to get the account balance in the client.  While the API supports it (v2 - https://dev.recurly.com/docs/lookup-account-balance), the c# client does not.  Am I missing something?  Seems like it should be pretty easy to add.

**Comment by 1TheMuffinMan** [comment]
@argystu Thanks for inquiring about this. I do not see it in the library either. I may be able to get this functionality implemented this week.

@bhelx Looks like this has been available since before API V2.5, but didn't make its way into the C# library. Seems like a simple implementation. I was thinking of pausing on subscription change object and completing this tonight. Thoughts?

**Comment by bhelx** [comment]
@1TheMuffinMan that sounds good. This was in api v2.3 I think. It's a pretty straightforward change. I believe in the other libraries I created an `AccountBalance` model for this.

**Comment by 1TheMuffinMan** [comment]
@argystu I will work on getting this in tonight for you.

**Comment by bhelx** [comment]
Thanks @1TheMuffinMan

I'll hold off the release for this last feature.

**Comment by argystu** [comment]
@1TheMuffinMan - thank you much!  I really appreciate it.

**Comment by bhelx** [comment]
@1TheMuffinMan You got an ETA on this feature? Would like to get out a release today but I can push to Monday.

**Comment by 1TheMuffinMan** [comment]
@argystu Just wanted to let you know that I started working on this last night and hope to have it done by Tuesday.

**Comment by argystu** [comment]
@1TheMuffinMan - Thanks for the heads up.

**Comment by argystu** [comment]
@bhelx - will you be putting out a new release now that this is complete?

**Comment by bhelx** [comment]
@argystu This will go out in 1.5.0: https://github.com/recurly/recurly-client-net/pull/235

I'm aiming for a release tonight. Tomorrow at latest.

**Comment by bhelx** [comment]
The release will be referenced here. Closing this issue now.
