### ISSUE TITLE
Error in readme sample

### ISSUE THREAD

**Issue by moritzgloeckl** [recurly/recurly-client-net#237]
Hi,

the account creation sample in the `readme` is missing a semicolon:

```
var account = new Account("123")
{
	FirstName = "John",
	LastName = "Smith"
};   <--------------------------- Missing semicolon
account.Create(); 
```

**Comment by 1TheMuffinMan** [comment]
@moritzgloeckl Thanks for reporting this

I've taken care of this. Feel free in the future to submit a pull request and we will merge it in.

**Comment by bhelx** [comment]
Thanks @moritzgloeckl !
