### ISSUE TITLE
No way to redeem gift cards?

### ISSUE THREAD

**Issue by jjwhite** [recurly/recurly-client-net#249]
It would appear that there is currently no way to redeem a gift card using the .NET client?  I noticed that the documentation does not show a C# option (https://dev.recurly.com/docs/redeem-gift-card) and I don't see anything in the GiftCard.cs file that would indicate that you can currently redeem with this library.  Am I missing something or is this a feature that is still pending.

**Comment by bhelx** [comment]
@jjwhite We still find missing features occasionally. I will take a look at this today and if needed, I'll submit a PR.

Also, I should note that if you are attempting to redeem a gift card as part of a signup or a purchase, you should consider looking at the new `/purchases` endpoint: https://dev.recurly.com/docs/create-purchase 

It's an all-in-one endpoint for subscriptions, adjustments, redemptions, etc. If you check the .NET example it includes a gift card redemption.

**Comment by bhelx** [comment]
So, I'm looking at [PR #241](https://github.com/recurly/recurly-client-net/pull/241) for GiftCard support. It does look like we missed that endpoint. I will put this on my schedule for today.

**Comment by bhelx** [comment]
@jjwhite Let me know if #250 looks good to you

**Comment by bhelx** [comment]
Closing with #250
