### ISSUE TITLE
Missing source code for version 1.3.2

### ISSUE THREAD

**Issue by sk8main** [recurly/recurly-client-net#257]
First of all thank you very much for the work on this repo. It has helped me greatly.

Over a year ago I had to create a fork of this library to add some additional functionality which I required and was missing from this version. 

We received a [security warning](https://dev.recurly.com/v2.8/page/net-updates) from Recurly informing us that we need to update our versions of the recurly-client-net api. For my situation I need to go from version 1.3.1 to 1.3.2. So I have come here looking for the source code for this release so that I can update my fork to the patched version, but can't find release/tag for 1.3.2 anywhere.

I know that we are pretty out of date with the recurly-client-net version, but currently don't have the resources to spend time bringing our application up to the latest version, but I do need to patch the forked version I currently have.

Could you please give me some information on how I would go about doing this.

Regards

Russell

**Comment by rachelquick** [comment]
Hi Russell, 
You can find the code at https://www.nuget.org/packages/recurly-api-client/ Let us know if you have any trouble!

**Comment by bhelx** [comment]
@sk8main The binaries are available on nuget, but not the source. We will be releasing the source to this repo soon but I'd suggest you contact support and they can get you a copy of the source you need.

**Comment by bhelx** [comment]
@sk8main if you have not seen it yet, the release was pushed here:
https://github.com/recurly/recurly-client-net/releases/tag/1.3.2
The `1.3.X` branch is here: https://github.com/recurly/recurly-client-net/tree/release_1_3
