### ISSUE TITLE
Issue in Coupon's 'Id' property

### ISSUE THREAD

**Issue by kirti-bhardwaj-onebcg** [recurly/recurly-client-net#274]
The value of Coupons's 'id' property is shown as 0 always.

**Comment by bhelx** [comment]
Which version of the library are you experiencing this on?

**Comment by kirti-bhardwaj-onebcg** [comment]
It is in the 1.9.1 version of library.

**Comment by bhelx** [comment]
Thanks, I'm seeing if I can reproduce this now.

**Comment by bhelx** [comment]
The fix will go out in the next release. Look for the link back here. Thanks so much for pointing this bug out!
