### ISSUE TITLE
Invoice's List method is not provided with FilterCriteria parameter

### ISSUE THREAD

**Issue by kirti-bhardwaj-onebcg** [recurly/recurly-client-net#275]

**Comment by NanashiGIT** [comment]
Hello,
could you please add the filterCriteria to the "GetAdjustments" method aswell?

We plan on using it but the current implementation doesn't allow the filtering we need. (e.g. begin_date and page size).

Thanks in advance!

**Comment by bhelx** [comment]
@NanashiGIT Sure, I plan to work on this this week.

**Comment by bhelx** [comment]
This fix will go out in the next release and will link back here.
