### ISSUE TITLE
 Account Acquisition

### ISSUE THREAD

**Issue by pshastov** [recurly/recurly-client-net#276]
Do you have plans to support Account Acquisition?
I can build it

**Comment by bhelx** [comment]
@pshastov It's not in my pipeline. It's a pretty simple feature though. If you want to give it an attempt, I'll happily review or provide assistance.

**Comment by pshastov** [comment]
@bhelx here it is https://github.com/recurly/recurly-client-net/pull/279

**Comment by bhelx** [comment]
@pshastov Thanks for taking this on!. I'll review it and get it into the next release.

**Comment by bhelx** [comment]
Closed with #279
