### ISSUE TITLE
Lists handling impovements suggestion

### ISSUE THREAD

**Issue by mbaranov** [recurly/recurly-client-net#28]
Hi,

I wanted to mention a couple of suggestions regarding how Recurly lists are accessed through the wrapper. 

It would be really nice if the following capabilities were available:
1. Abilility to override default page size (that is specified in configuration settings) on a method-by-method basis
2. Abililty to optionally specify StartUrl in methods that return paged lists (in order to be able to leverage the internal paging support for higher level APIs built using this wrapper library).

Thanks!

**Comment by bhelx** [comment]
@mbaranov is this something you are still interested in doing?

**Comment by mbaranov** [comment]
We ended up doing a custom wrapper around the REST API in our project. So no, the need is no longer there.
