### ISSUE TITLE
Exception in Invoice's List & Get methods

### ISSUE THREAD

**Issue by kirti-bhardwaj-onebcg** [recurly/recurly-client-net#284]
All the Invoice's List & Get methods throw an ArgumentException - 'Requested value 'Mn' was not found'.
(The value in exception may vary)

**Comment by bhelx** [comment]
@kirti-bhardwaj-onebcg I had an idea of what was wrong here but I cannot reproduce. Could you tell me what version of the client you are using and maybe what the corresponding xml is that breaks the parser?

**Comment by bhelx** [comment]
Going to close until we can reproduce. Please feel free to re-open.
