### ISSUE TITLE
Product code not available in C# API?

### ISSUE THREAD

**Issue by AdamYEG** [recurly/recurly-client-net#29]
product_code is available for adjustments through the api xml- yet there is no property in the adjustments.cs class to get/set the value?  I'm wondering why this is?

I have a plan add on with an "add-on code" of "XYZ" in the recurly UI.  When a payment is processed - I am getting a web hook telling me of the successful payment.  I then use the API to get the adjustments on that invoice.  When I pull the adjustments, I'm trying to find out what the adjustment is for by either the accounting_code or the product_code (unique).  In this case - I get a adjustment with origin of add_on, but the accounting_code is blank and the product_code is not available in the C#.  When I pull report though recurly UI - I see add-on code is set as product_code, so I assume that's the code I need to use?  I included it in my local project (get only), but was wondering why this is left off the project?  How am I supposed to uniquely identify my add_on for processing via the api/C#?

Thanks!

**Comment by cbarton** [comment]
Hey @AdamYEG, sorry about the *long* delay. I am going through and adding some missing properties right now and will add this as well.
