### ISSUE TITLE
Add a Transaction.GetSubscription() (nullable) method

### ISSUE THREAD

**Issue by Sire** [recurly/recurly-client-net#294]
Doesn't all (or at least almost all) transactions have a subscription?  There is no `Transaction.GetSubscription()` method, even though the subscription uuid is sent with every webhook that includes transactions.
It can return a nullable Subscription and return null for edge cases where no subscription exists.

An invoice can also have several subscriptions (in theory, I've never seen it), so we we are forced to jump through several hoops to make sure we get the right the subscription:
`var subscription = transaction.GetInvoice().GetSubscriptions().OrderByDescending(s => s.ActivatedAt)..Where(s => s.State == Subscription.SubscriptionState.Active).FirstOrDefault();`
If there is an easier way, let me know. Thanks!

**Comment by rachelquick** [comment]
Hi Sire - not all transactions will have a subscription. There are one-time purchases and verification transactions that will not be related to a subscription UUID. 

Our support team (support@recurly.com) can provide more details if you want us to look at specific items.

**Comment by Sire** [comment]
Thanks Rachel. In our case there is always a subscription, and getting it from a transaction is needlessly complex. A nullable GetSubscription() method or nullable Subscription property would be great. Please consider this.
You've solved it like this in the past, for instance the nullable Transaction.Invoice property.

**Comment by rachelquick** [comment]
It'd be great if you can submit this to support@recurly.com, so we can formally track this as a feature request and get you updates. In the meantime, I'll mark this issue closed.

**Comment by drewish** [comment]
One small note, in recent versions of the API it's now a plural subscriptions since the purchases endpoint allows multiple subscriptions to be purchased in one transaction.
