### ISSUE TITLE
Re-Open #284 : Exception in Invoice's List & Get methods

### ISSUE THREAD

**Issue by kirti-bhardwaj-onebcg** [recurly/recurly-client-net#295]
@bhelx FYI 
We are using the 1.11.0 version of Client Library. Please find the attachment of corresponding XML of an invoice.
 [XML_Invoice.txt](https://github.com/recurly/recurly-client-net/files/1941259/XML_Invoice.txt)

**Comment by aaron-suarez** [comment]
@kirti-bhardwaj-onebcg Is this still a problem for you? If you're no longer seeing an exception that you can copy and paste into a comment on this issue, I'm going to go ahead and close it out as it is unactionable.

**Comment by aaron-suarez** [comment]
Closing this out as inactionable. Please feel free to re-open with more information and the exception text.
