### ISSUE TITLE
usage id on Get usage

### ISSUE THREAD

**Issue by unnijeevan** [recurly/recurly-client-net#304]
As per the end point documentation you need only 2 parameters for Get request of an Usage record object
https://dev.recurly.com/v2.2/docs/usage-record-object

But in the .Net client  it is asking for a usage id of type long 
public static Usage Get(string subscriptionUuid, string subscriptionAddOnCode, long usageId);

I can get the list and get first or default as a work around but wondering what is the usageId. Doesn't subscriptionUuid and subscriptionAddOnCode uniquely identifies an Addon Usage?

**Comment by drewish** [comment]
The application we use for our docs has some limitations for describing the format of responses. We'd tried to work around that by putting in some "Object" pages that document response using the tool's input format... I think, as demonstrated by your question, it causes more confusion than it is worth. The  correct link for the method you cited is https://dev.recurly.com/v2.2/docs/lookup-usage-record. E

ach add-on can have multiple usage records associated with it so you could use https://dev.recurly.com/v2.2/docs/list-add-ons-usage to list them out.

**Comment by unnijeevan** [comment]
Thanks @drewish . So basically I tried creating a usage using subscription uuid and addon code which I suppose is same as the Post end point .  Later when  I try to get the addons for the same subscription and addon using the list end pint , the  Id property of the usage object is null.  I can't really call the  https://dev.recurly.com/v2.2/docs/lookup-usage-record with null usage id.

Is Id of the usage something auto gernerated when you call usage.create() or is it something we have to assign ourselves

**Comment by bhelx** [comment]
@unnijeevan `Id` should be a property on the Usage object, although our code seems to be parsing it in a strange way: https://github.com/recurly/recurly-client-net/blob/5ecf8d8847a91173e3093ef5c6b855fc87cdfac7/Library/Usage.cs#L108

I believe this is because Id was not provided as an xml attribute at the time.

Could you perhaps tell us which version of the .NET library you are using and show some example code to demonstrate the problem?

**Comment by unnijeevan** [comment]
@bhelx 
I am using 1.12 version 
The code is something like 
  var usages = Recurly.Usages.List(subUuid, addonCode);
```
  if(usages?.NotNullOrEmpty() ?? false)
  {
          //Here Id is null. I would assume the Id was generated in the else create function in else condition below
            var usage = Recurly.Usages.Get(subUuid, addonCode, usages.FirstOrDefault().Id.Value);
            usage.Amount = quantity;
            usage.Update();
  }
  else
  {
       //At first the else condition is hit and this usage gets created. It works fine and i can see that when I login to your site.
            var usage = new Recurly.Usage(subUuid, addonCode);
            usage.Amount = quantity;
            usage.Create();
  }
```

**Comment by bhelx** [comment]
@unnijeevan please see #305 for the fix.

**Comment by unnijeevan** [comment]
@bhelx 
Thanks , I will wait for the request to be merged and package to be built

**Comment by bhelx** [comment]
@unnijeevan thanks again for reporting. I'm aiming to merge a couple bug fixes and do a patch-level release next week.
