### ISSUE TITLE
Subscription.Coupon throws an ArgumentNullException, if _couponCode is null.

### ISSUE THREAD

**Issue by jamesbar2** [recurly/recurly-client-net#312]
When calling [`Subscription.Coupon`](https://github.com/recurly/recurly-client-net/blob/master/Library/Subscription.cs#L202), the Recurly client will make a request to fetch the coupon, even if the underlying `_couponCode` is null.  This might not be an issue, except while forming request in [`Coupon.Get(couponCode)`](https://github.com/recurly/recurly-client-net/blob/master/Library/Coupon.cs#L538), `Uri.EscapeDataString(couponCode)` is called without ever checking if the `couponCode` is null or empty.  This results in an `ArgumentNullException` from `Uri`.

To patch this on our end, I'm surrounding `Subscripton.Coupon` with a try/catch(ArgumentNullException)`.  I'll look at creating a PR to fix the issuethough.

**Comment by bhelx** [comment]
@jamesbar2 I think you are correct. It should have a case for when `_couponCode` is null. I'd be happy to review any PR you make for this. If you don't have time to get to it, I can put this in my backlog as well.

**Comment by jamesbar2** [comment]
@bhelx I just forked it and am making the change now.  I assume `Coupon` should just return null.

**Comment by bhelx** [comment]
Yeah, that sounds good.

**Comment by jamesbar2** [comment]
@bhelx Posted a PR for it, #313.  Let me know if you'd like anything changed.  Thanks for your help.

**Comment by bhelx** [comment]
@jamesbar2 we really appreciate you taking this on. I have a release planned for today. I'll see if i can squeeze this feature in.

**Comment by bhelx** [comment]
Closed with #313

**Comment by jamesbar2** [comment]
Thanks @bhelx, happy to help 😄
