### ISSUE TITLE
Exception when card type is nil 

### ISSUE THREAD

**Issue by adeelhasan** [recurly/recurly-client-net#318]
In BillingInfo.cs

CardType = reader.ReadElementContentAsString().ParseAsEnum<CreditCardType>();

fails when credit card type is nil. This started happening very recently (about a week ago.) I have put a null check around this to get it to work and can submit, but were there any changes in the main recurly api that would cause this to start happening?

**Comment by drewish** [comment]
Are you checking the billing info type? For instance PayPal and ACH billing info won't have a card type.

**Comment by adeelhasan** [comment]
not checking the card type explicitly, but the failure is when there is a valid card type ... oddly enough, seems to be failing for Visa / MC / Discover, and not for Amex.

I am not passing the card type when setting the billing info, previously this was working fine. That said no one else is reporting the problem, so the probability of it being something at my end is very high.

**Comment by drewish** [comment]
Could you provide a little example code to show how you're accessing the billing info? I'm wondering if it's an issue with another object that nests the billing info inside it.

**Comment by adeelhasan** [comment]
sure, let me also get the xml that comes back, so that you can have the full information. will do so by end of day. thanks.

**Comment by adeelhasan** [comment]
hi, I see that you have checked in accounting for the possibility of a null ... to circle back though, the card type had been read in as whitespace when the problem happened. it happened for an account which had no billing info entered as yet. Once I enter some billing info, even though I subsequently clear out the billing info, it no longer comes back as whitespace.

thanks for your attention, can go back to using the nuget package.

**Comment by bhelx** [comment]
Thanks for updating us @adeelhasan . Sorry about this issue.
