### ISSUE TITLE
Datetime Parsing not utc

### ISSUE THREAD

**Issue by unnijeevan** [recurly/recurly-client-net#338]
https://github.com/recurly/recurly-client-net/blob/60e750f075a3c5ce2ca5f4574c593edfaa83ba57/Library/Usage.cs#L140

Currently  I am trying the following code to update the amount for usage based addons 
```
 var usage = Recurly.Usages.List(subUuid, addonCode).OrEmpty().FirstOrDefault();
  if(usage!=null)
  {
         
            usage.Amount = quantity;
            usage.Update();
  }

```
I think the issue is that Datetime.Parse used to get recording timestamp and usage time timestamp doesn't return date in UTC . However when in the WriteXML it is just converted using DatetimeToString("s").  So if I am passing a local date time , which is something I got when I retrieved the usage , it throws an error. I think API expects it in UTC and the current time in AEST when read as UTC will be in future and it throws an error.

This forces me to write the above code as  so that timestamps are ignored
```
{  
         
           usage.Amount = quantity;
           usage.UsageTimestamp = null;
           usage.RecordingTimestamp = null;
            usage.Update();
  }
```

Is there a better fix for this so that I don't have to set the properties which I don't want to update

For eg : 

> DateTime.Parse("2018-09-13T00:43:14Z").ToString("s")  

will give the result 

> 2018-09-13T10:43:14 

instead of 

> 2018-09-13T00:43:14Z

**Comment by aaron-suarez** [comment]
Hey there @unnijeevan! I'll take a look at this and see if I get the same behavior. If so, we'll take a look and see if we can find a solution
