### ISSUE TITLE
Error when updating with the PlanIntervalUnit = IntervalUnit.Days

### ISSUE THREAD

**Issue by duranmg** [recurly/recurly-client-net#344]
I am using .net client 1.13.1
When I update a Plan with IntervalUnits.Months it works fine...butwhen I change to IntervalUnit.Days I get an error.  

The information being saved is not valid.
   at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, WriteXmlDelegate writeXmlDelegate, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate reseponseDelegate)
   at Recurly.Plan.Update()
   at UrbanAir.Web.Azure.Functions.Services.RecurlyService.SavePlan(String json).

**Comment by aaron-suarez** [comment]
@duranmg I'll be happy to take a look at this for you. Do you happen to have a code snippet you can share so I can try to reproduce this error?

**Comment by aaron-suarez** [comment]
Hi @duranmg. I went ahead and tried to reproduce this error on my own. Here's my code snippet:

```C#
            var plan = Plans.Get("gold");
            plan.PlanIntervalUnit = Plan.IntervalUnit.Months;
            plan.Update();
```

I then ran this

```C#
            var plan = Plans.Get("gold");
            plan.PlanIntervalUnit = Plan.IntervalUnit.Days;
            plan.Update();
```

Both worked on my sandbox site how I have it configured. Is there any additional information or code snippet(s) you can provide to help me reproduce the problem?

**Comment by aaron-suarez** [comment]
I did a little more digging. I think that your error has something to do with the last Release Note for v2.13:

```
Change Plans PUT request/response
• Modifying <plan_interval_unit> will result in an error: Plan interval unit cannot be edited once a plan is created.
• Modifying <plan_interval_length> will result in an error: Plan interval length cannot be edited once a plan is created.
```

https://dev.recurly.com/page/api-release-notes#v213-release-notes

I think that I was using an older version of the API when I did that test I described above. As far as I know, you're not supposed to be able to change the interval after a plan is created. If you need to update a plan's interval, please contact Recurly support and they should be able to walk you through the steps to do that.
