### ISSUE TITLE
Recurly V3 API GA?

### ISSUE THREAD

**Issue by dmcweeney** [recurly/recurly-client-net#398]
Hi,

I'm wondering when is it expected that the current beta 3 development will go GA. Specifically interested in the ASP.Net Core implementation.

Thanks

Donal

**Comment by dsaulet** [comment]
Hi Donal,

We are targeting the end of the year for the v3 API to go GA. However, it is currently available via early access if you'd like to start using it now. Several of our integration partners are currently using it in production. Here's a [link](https://dev.recurly.com/page/recurly-v3-api-early-access) to the Early Access info page which has links to the v3 JSON API documentation as well as links to the various client libraries we're currently supporting for it, including .NET Core.
