### ISSUE TITLE
Plans for .NET Core / Modernizing the project

### ISSUE THREAD

**Issue by joaopgrassi** [recurly/recurly-client-net#399]
We use Recurly in one of our main services, an ASP.NET Web API. Going forward, we are doing efforts to modernize our solution having the ultimate goal of moving to .NET/ASP.NET Core.

That is a very complicated and painful migration but somewhat doable. My research and experience so far as a "first-step" migration have been:

- Migrating project from `packages.config` to `PackageReferences`
- Migrate project to the new SDK-style csproj
- Multi-target libraries to `netstandard` and `net46`

Since this is a package, I think the community can benefit a lot if we modernize the project to get out of the old `packages.config` and the awful old `csproj` format.

The coolest thing is that migrating to the new format enables us to do multitargeting. The code can target both `.NET Standard` and `NET Fx`, making it easy for people on .NET Core to use, without having to download a dll and all that.

So, my question is: Is this in your roadmap? I can and I'm interested in helping moving it forward, but I don't want to spend time on it if it's not something your org is wanting to do as well, mainly because we'll need to do reviews and all that.

Let me know your thoughts.

Cheers.

**Comment by aaron-suarez** [comment]
@joaopgrassi Thank you for your comment!

The master branch of this repo is the .NET library for V2 of our API which targets .NET Framework. The new V3 API (which, among other differences, uses JSON instead of XML) targets .NET Core.

If you haven't already checked that out, be sure to here https://dev.recurly.com/page/recurly-v3-api-early-access

Just to be clear, is your question based on the V2 (master branch) library or the V3 (3_0_0_beta branch) library?

**Comment by bhelx** [comment]
@joaopgrassi We are not going to support dotnet core with this version of the library. We are instead focusing our efforts on the next version (which will also take advantage of our new JSON API). Refer to @aaron-suarez's comment for details on that. If you are interested in trying out the new version of the library, drop us an email and we can provide you with advice: ben@recurly.com, domino@recurly.com.

**Comment by joaopgrassi** [comment]
Hey @aaron-suarez,

Sorry I didn't see that branch. Yes, I was referring to the master branch. I looked briefly at that and it seems much nicer 👍 

Just as an idea: Maybe update the README.md on master, to indicate that you guys are working on it. Right now it just says that you don't support it and it seems more or less like an abandoned project. At least that's how I felt and the reason why I opened the issue. 

I will see if I can try the new version. Things are a bit messy right now so.. hehe. 

Thanks!

**Comment by bhelx** [comment]
@joaopgrassi We'll be rolling out that messaging soon. Right now we are in a phase of testing and trying to make sure we release the new library with an interface we can confidently support for years to come. We would love to get your feedback on any changes you think should be made with the new version if you find the time.
