### ISSUE TITLE
Add 'protected' to constructors for RecurlyEntity

### ISSUE THREAD

**Issue by stweedie** [recurly/recurly-client-net#411]
This is mainly so that we can properly mock Recurly objects for testing. Without providing a protected (or public) constructor, we are unable to mock several objects. Adding a protected constructor allows the following:

```c#
// change from "internal" -> "protected internal"
protected internal CouponRedemption()
{
}
```
```c#
public class TestRecurlyCouponRedemption: Recurly.CouponRedemption
{
	public TestRecurlyCouponRedemption(string couponCode, int amountInCents)
	{
		CouponCode = couponCode;
		TotalDiscountedInCents = amountInCents;
	}

	public new int TotalDiscountedInCents { get; set; }
	public new string CouponCode { get; set; }
	public new string Uuid { get; set; }

	public TestRecurlyCouponRedemption SetId(string id)
	{
		Uuid = id;
		return this;
	}
}
```

Therefore we can test our handling of coupon redemptions. 

Note: I have a branch on my personal fork that I can use to open a PR for this issue. I just wasn't sure if this idea would be accepted, but I know there are at least a few reasonable use cases where we would want to be able to mock some of the data structures coming from Recurly.

**Comment by stweedie** [comment]
Alternately, and this might be more helpful in general, would you be willing to accept a PR to add interfaces for most recurly entities? Then we could provide our own implementation when needed (for mocking), but it would leave the entirety of the underlying implementation unchanged.

**Comment by aaron-suarez** [comment]
Hi @stweedie! Thanks for bringing this up. I won't know for sure until we can review the code, but it seems like the original suggestion of making the properties `protected internal` should be just fine, especially if it helps for testing. If you think it would be better to add interfaces, that's an option we can look at as well, but it sounds like it would be more work to get to the same result, wouldn't it?

We'll be happy to review any PR you send to us, and the accessors you describe would likely be accepted. Go ahead and open it up and we can talk regarding the actual code changes. Thanks!

**Comment by stweedie** [comment]
Alright I have opened a PR for the protected constructors.

I have since realized that there is some difficulty in mocking some of the instance methods, which is why I suggested the interface modification.

**Comment by aaron-suarez** [comment]
Do you have a code sample of how you would mock it? I'd like to better understand what you're doing so I can verify the solution

**Comment by stweedie** [comment]
so here would be an example, where we are trying to handle converting from a Recurly invoice to our own custom invoice model (where everything is stored as decimals instead of cents)

```c#
// TestRecurlyInvoice
public class TestRecurlyInvoice : Recurly.Invoice
{
	public TestRecurlyInvoice(string currencyCode = "$") : base()
	{
		Currency = currencyCode;
	}

	public TestRecurlyInvoice SetSubtotal(int subtotal)
	{
		SubtotalBeforeDiscountInCents = subtotal;
		RecalculateTotals();
		return this;
	}

	public TestRecurlyInvoice SetTax(int tax)
	{
		TaxInCents = tax;
		RecalculateTotals();
		return this;
	}

	public TestRecurlyInvoice SetDiscount(int discount)
	{
		DiscountInCents = discount;
		RecalculateTotals();
		return this;
	}

	private void RecalculateTotals()
	{
		SubtotalInCents = SubtotalBeforeDiscountInCents - (DiscountInCents ?? 0);
		TotalInCents = SubtotalInCents + TaxInCents;
	}
}
```

```c#
var invoice = new TestRecurlyInvoice();

invoice
	.SetSubtotal(5000)
	.SetDiscount(400)
	.SetTax(125);

var userInvoice = _service.ConvertFromRecurly(invoice);

userInvoice.Subtotal.Should().Be((decimal)50.00);
userInvoice.DiscountTotal.Should().Be((decimal)4.00);
userInvoice.TaxTotal.Should().Be((decimal)1.25);
userInvoice.Total.Should().Be((decimal)47.25);
```

**Comment by stweedie** [comment]
This is all assuming of course that interfaces aren't available. In the above case, it would be much more beneficial to have:

```c#
// added to Recurly namespace
public interface IInvoice
{
	string Uuid { get; }
	string Currency { get; }
	int SubtotalBeforeDiscountInCents { get; }
	int? DiscountInCents { get; }
	int SubtotalInCents { get; }
	int TaxInCents { get; }
	int TotalInCents { get; }
	string TaxRegion { get; }
	decimal? TaxRate { get; }
}

public class FakeInvoice : Recurly.IInvoice
{
	public string Uuid { get; set; }
	public string Currency { get; set; }
	public int SubtotalBeforeDiscountInCents { get; set; }
	public int? DiscountInCents { get; set; }
	public int SubtotalInCents { get; set; }
	public int TaxInCents { get; set; }
	public int TotalInCents { get; set; }
	public string TaxRegion { get; set; }
	public decimal? TaxRate { get; set; }
}

public class SampleService
{
	public CustomerInvoice ConvertToCustomerInvoice(Recurly.IInvoice recurlyInvoice)
	{
		// code to test
	}
}

[Fact]
public void ConvertToCustomerInvoice_TestConversion()
{
	var fakeInvoice = new FakeInvoice()
	{
		Uuid = "FAKE_ID",
		SubtotalBeforeDiscountInCents = 1200,
		DiscountInCents = 0,
		// etc
	};

	var result = _sampleService.ConvertToCustomerInvoice(recurlyInvoice);
	result.Subtotal.Should().Be(12.00);
}
```

With interfaces, we wouldn't modify any Recurly code, but we would be able to test our interactions with the same structure as the result we would expect from Recurly. Plus, then we can involve covariance

**Comment by aaron-suarez** [comment]
The solution of having protected constructors would be needed even if we do add in interfaces, correct?

**Comment by stweedie** [comment]
With interfaces, we could provide our own implementation, so we wouldn't need protected constructors.

**Comment by aaron-suarez** [comment]
If you feel that the interfaces solution is better overall for your testing and mocking purposes, I'd rather  we go ahead and implement that rather than the protected constructors solution. If you already have these interfaces written, you could go ahead and open that as a PR in lieu of #413. Apologies if it caused more work for you to open the first PR just to do a second PR, but it seems like you'd prefer the interface solution more than the accessor solution anyway.

Thanks for your contribution. If you change your mind about which solution is better, let me know and I'll take a closer look at #413, but otherwise I look forward to seeing your interfaces PR.

**Comment by stweedie** [comment]
It's no problem. I actually did the protected constructors first but then found use cases that were not solved by it.

I'll close 413 and have a new one up in the next few days.

Thanks

**Comment by joannasese** [comment]
Referencing PR #421, this issue is closed.
