### ISSUE TITLE
Recurly client legacy configuration issue

### ISSUE THREAD

**Issue by subterraneanbob** [recurly/recurly-client-net#417]
**Describe the bug**

I upgraded Recurly client to the version 1.15.7 (from 1.14.1) and now some methods, like retrieve existing plans, throw exception:

```
The Recurly client has has no configuration initialized, please add your settings to web/app.config or call Recurly.Configuration.SettingsManager.Initialize(args)
```

I use legacy method of configuring with web.config, which I believe is still supported. Also, I am certain that the issue has nothing to do with my configuration as it worked fine with previous versions of the library.

Here is the part of stack trace:
```
[Exception: The Recurly client has has no configuration initialized, please add your settings to web/app.config or call Recurly.Configuration.SettingsManager.Initialize(args)]
   Recurly.Configuration.Settings.get_PageSize() in /Users/asuarez/code/v2/clients/dotnet/Library/Configuration/Settings.cs:60
   Recurly.RecurlyList`1..ctor(HttpRequestMethod method, String url) in /Users/asuarez/code/v2/clients/dotnet/Library/List/RecurlyList.cs:13
   Recurly.Plans.List(FilterCriteria filter) in /Users/asuarez/code/v2/clients/dotnet/Library/Plan.cs:482
```

I investigated what may cause the problem and it turns out that `Configuration.Settings` class fails to read configuration values from *web.config* and fails silently at 
https://github.com/recurly/recurly-client-net/blob/a1791ee4d7632998c9215c6ab6690a3cd8e8473b/Library/Configuration/Settings.cs#L131

As I understand, it happens due to the mismatched section name for request timeout parameter: there is `timeoutMilliseconds` in configuration propery but `requestTimeoutMilliseconds` in the methods code and it causes NRE - https://github.com/recurly/recurly-client-net/blob/a1791ee4d7632998c9215c6ab6690a3cd8e8473b/Library/Configuration/Section.cs#L65
When I changed `requestTimeoutMilliseconds` to `timeoutMilliseconds`, the issue disappeared.

**To Reproduce**

To reproduce, use legacy method for defining api key and subdomain on web.config:
```xml
<configSections>
  ..
  <section name="recurly" type="Recurly.Configuration.Section,Recurly" />
</configSections>
..
<recurly apiKey="my-api-key" subdomain="my-subdomain" />  
```
> Do **not** statically initialize the library by calling `Recurly.Configuration.SettingsManager.Initialize()`.

After that, attempt to invoke `Recurly.Plans.List()` - it throws an exception.

**Expected behavior**

`Recurly.Plans.List()` does not throw and returns a list with available plans.

**Your Environment**

- Which version of this library are you using?
1.15.6, 1.15.7
- Which version of dotnet are you using?
.NET Framework 4.7.2

**Comment by aaron-suarez** [comment]
Thank you for the detailed bug report @subterraneanbob. We will investigate.

**Comment by aaron-suarez** [comment]
@subterraneanbob Please note that using the legacy method can be dangerous depending on your setup. The primary problem is that storing your API key in a plaintext file on your server is a very bad idea from a security perspective. An attacker (or a malicious employee) with access to the server can just read the file and start performing operations via the Recurly API. Instead, it is highly recommended to use an encrypted secrets store. Please be sure to take all proper precautions to safeguard your API keys.

**Comment by subterraneanbob** [comment]
@aaron-suarez Thanks for your concern. We protect Recruly API key (all sensitive information in fact) by [encrypting web.config with RSA](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.rsaprotectedconfigurationprovider?view=netframework-4.7.2).

**Comment by aaron-suarez** [comment]
Thank you for the additional context. We will prioritize work on a fix for this issue and have a patch as soon as we can.
