### ISSUE TITLE
merchant reported listing account subscriptions only provides active subscriptions

### ISSUE THREAD

**Issue by whiteotter** [recurly/recurly-client-net#42]
https://docs.recurly.com/api/subscriptions#list-account-subscriptions

Should provide all subscriptions, regardless of subscription state

**Comment by bhelx** [comment]
The library specifies a default of `All`:

https://github.com/recurly/recurly-client-net/blob/master/Library/Account.cs#L214
```csharp
public RecurlyList<Subscription> GetSubscriptions(Subscription.SubscriptionState state = Subscription.SubscriptionState.All)
```
So this would be a bug or their library is potentially old.

I took an account with both active and expired subscriptions, pulled down the subs then printed their state:

```csharp
var account = Accounts.Get("newtest");

var subscriptions = account.GetSubscriptions();
while (subscriptions.Any())
{
  foreach (var subscription in subscriptions)
     Console.WriteLine("Subscription: " + subscription.State);
     subscriptions = subscriptions.Next;
}
```

It printed both expired and active states so I'm assuming the `All` flag is working.

Closing for now, please re-open if we need to look at this again.
