### ISSUE TITLE
Transactions Get By Start DateTime

### ISSUE THREAD

**Issue by tcclancy** [recurly/recurly-client-net#44]
I would like to the ability to query transactions and accounts at a specific date and time down to the millisecond or whatever the most accurate unit is available in your data structure.  A common query would be able to supply a specific start date time as in input parameter.  Another parameter would be the direction of data: ascending or descending (forward or backward). Another parameter might be read-only, since this may speed up the call and take less overhead depending upon the underlying data structure.

Example: If you  wanted to return 200 transactions to start at August 1, 2014 at two fifteen pm 
it would be expressed as: 08-01-2014 14:15:00
DataDirection = 1;
PageSize =200;
Transactions.GetByStartTime (DateTime, Data Direction, PageSize)

This would return 200 records starting at the time indicated. Depending upon the type of business 200 records may be weeks or might be a couple of seconds.   Based on what is returned I can make another call using the start time being the same or a slight increment of the last record supplied by the previous call.  

Record set returned : (using a base of zero)
Record 0              2014-08-01 14:15:00 143
Record 1              2014-08-01 14:15:00 350
Record 2              2014-08-01 14:15:01 080
…
Record 199          2014-08-01 14:15:05 000   (last record returned)

I would take the last record returned from the first call and add milliseconds to it.

08-01-2014 14:15:05 001
DataDirection = 1;
PageSize =200;
Transactions.GetByStartTime (DateTime, Data Direction, PageSize)

This would get around the pagination issue

**Comment by MuffinMan10110** [comment]
This sounds like a useful feature, however the limiting factor is not in the .NET library, but in the Recurly API. It doesn't support this type of granularity. You may want to reach out to support@recurly.com to see if they'd be willing to support it through the API, if they do I'd be happy to implement this for you.

It essentially only supports state, type and paging info.

You can check out the supported query options here https://docs.recurly.com/api/transactions#list-transactions

**Comment by bhelx** [comment]
I think @MuffinMan10110 provided the correct answer here. @tcclancy let us know if you still need help or need this feature in the API.
