### ISSUE TITLE
Creating a subscription fails with `three_d_secure_action_required` although secure action has been completed 

### ISSUE THREAD

**Issue by moritzgloeckl** [recurly/recurly-client-net#444]
Hi,

I'm trying to create a subscription, however, it fails with the error code `three_d_secure_action_required` - on new accounts. 

First we're trying to setup the `BillingInfo` for the customer. It then fails with `three_d_secure_action_required` which is intended I think. We then let the customer run through the flow and re-create the `BillingInfo` with the correct `ThreeDSecureActionResultTokenId` like this:

```
var billingInfo = new BillingInfo(account);
billingInfo.TokenId = recurlyToken;
billingInfo.ThreeDSecureActionResultTokenId = threeDSecureActionTokenId;
UpdateBillingInfo(billingInfo);
```

It works and we let the user preview the subscription. Once the user clicks on our Buy Now button we call `Subscription.create()`, however it fails with the `three_d_secure_action_required` error. The library does not support sending the ThreeDToken again it seems, although the [integration guide](https://dev.recurly.com/page/recurly-3d-secure-2-integration-guide) says 

> three_d_secure_action_result_token_id is a valid parameter on the Create Billing Info endpoint and on any Recurly API endpoint that accepts a Billing Info, including Create Purchase, Create Subscription, Update Subscription, Create Account, Collect Invoice, Create Gift Card

Is this a bug in the library, a bug in the API or are we doing something wrong here?

We're using dotnet 4.7.2, Recurly library v1.16.2, Recurly.js, our Recurly site is in development mode and we are using Stripe test endpoints.

**Comment by neuronicnobody** [comment]
Hi @moritzgloeckl,

Is it the case that Subscription.create() is not accepting a 3DS Action Result Token ID or that you're trying to pass in a previous ID obtained as part of the Create Billing Info step and getting an error? If it's the latter please note that's invalid. We added a clarification to the integration guide yesterday on this matter

> It is also invalid to mix and match 3DS Action Result Token Ids between different API endpoints. For example, A 3DS Action Result Token Id obtained as part of the authentication process with the Create Account / Billing Info endpoint, can not be passed into the Create Subscription endpoint. A new token must be generated in this case if the endpoint requires 3DS2 authentication.

**Comment by moritzgloeckl** [comment]
Hi @neuronicnobody,

thanks for your answer. I'm more or less addressing the first problem, that `Subscription.create()` is not accepting a 3DS Action Result Token ID. I've already read the clarification you added, however, I'm not quite sure what we're supposed to do then?

If the customer adds their Billing Info and their getting back the `three_d_secure_action_required` error, we're sending them through the 3DS flow (iframe pops up, complete verification). Now the customer is able to preview the subscription, and agrees to subscribe. Now we're getting another `three_d_secure_action_required` error. So what are we supposed to do now? Send the customer through the 3DS flow again? This doesn't seem right to me to be honest. Also as I mentioned I don't think this library implements this behavior correctly currently, since it's not possible to pass the 3DS token to `Subscription.create()`.

What I would expect (also from my experience as a customer of other sites), is that 3DS is triggered on adding the `BillingInfo` and if that was successful, the customer is not bothered again when agreeing to subscribe.

**Comment by neuronicnobody** [comment]
@moritzgloeckl 

Thanks for the extra details.  I can confirm that  Subscription.create() *should* accept a `three_d_secure_action_result_token_id` via the Billing Info object, so we'll take another look at this gap in the client library and address it accordingly.

As for the use case you're describing, if you receive the `three_d_secure_action_required` error a second time (when creating the subscription) the correct action would be to send the customer through the 3DS Authentication flow again, obtain the new `three_d_secure_action_result_token_id` and pass it through to the create subscription endpoint. I completely agree that this is not ideal from a customer experience perspective, but the decision as to whether a challenge is requested or not ( presence of the action required error) is completely up to the customers Issuing bank. Therefore, it is recommended that your integration is prepared to handle the error and walk the customer through authentication for any API request that updates the billing info, the amount of the subscription ( Update Subscription ), or in general any request that results in a card Authorization or Transaction.

**Comment by neuronicnobody** [comment]
@moritzgloeckl 

Just double checked and the BillInfo appears to be a public property and writeable:

https://github.com/recurly/recurly-client-net/blob/master/Library/BillingInfo.cs#L113
https://github.com/recurly/recurly-client-net/blob/master/Library/BillingInfo.cs#L457
Library/BillingInfo.cs:457

Note: the `three_d_secure_action_result_token_id` is passed in via the Billing Info object when you create the subscription

**Comment by moritzgloeckl** [comment]
@neuronicnobody 

Thanks for your answer. It seems a bit strange that the customer needs to be routed through the whole 3DS flow again, however, I understand that it is up to the bank to decide.

You mentioned that the token is passed in via the BillingInfo, but how should we attach the BillingInfo to the Subscription? The Subscription does not have a BillingInfo property...

**Comment by neuronicnobody** [comment]
@moritzgloeckl 

As far as the double authentication, we wouldn't expect that to be a frequent occurrence, but it's a possibility that needs to be handled if it does happen.

The Billing Info is nested under the Account on the Create Subscription endpoint.
https://dev.recurly.com/docs/create-subscription

Here's an example of usage from our 3DS2 example from the Ruby repo: ( unfortunately no example for .NET at the moment)
https://github.com/recurly/recurly-js-examples/blob/master/api/ruby/app.rb#L39

**Comment by joannasese** [comment]
@moritzgloeckl I'm closing this issue for now. If you're still having issues, we can reopen.

**Comment by eduard-tapkey** [comment]
Hi all,
I will reopen this old thread just to ask if double 3Ds flow is still expected. To explain in details:
1) We create an account and add billing info with token
2) This throws a 3d secure exception (expected) 
3) We continue with 3Ds flow and get back to updating billing info with 3d token as well
4) Everything goes through and billing info is updated for the account
5) We want to create a subscription for the same account
6) We create a subscription for the same account as above (with billing info filled out already)
7) 3Ds flow is triggered again
I know I might be asking the same thing as above but is this flow correct? As a customer I would find it suspicious that for one payment I need to go through 3ds twice. What would be the correct way to do this?
For testing purposes I'm using Recurly 3ds card: 4000 0000 0000 3220

Thank you! :)
