### ISSUE TITLE
ArgumentOutOfRangeException thrown when trying to iterate on Pager object

### ISSUE THREAD

**Issue by BenGoldberg** [recurly/recurly-client-net#445]
Hi there,

As stated above, we are getting an ArgumentOutOfRangeException when trying to iterate on a pager object. Specifically, we are trying to grab a list of subscriptions for an account. Here is the code:

`var pager = _client.ListAccountSubscriptions($"code-{accountCode}", state: "live");`

In the test we ran, there were no live subscriptions in the account we tried on. However, I would still except to be able to iterate over such an object.

The version of the library we are using is 3.0.0-beta.5. Please let me know if I can provide more information!

**Comment by bhelx** [comment]
Thanks for the details @BenGoldberg ! I'll try to repro today.

**Comment by bhelx** [comment]
@BenGoldberg can you paste a stacktrace if you have it?

**Comment by bhelx** [comment]
I can't seem to repro on 3.0.0-beta.6. Tried it on a new account with new subs.

**Comment by BenGoldberg** [comment]
I'm trying to update to 3.0.0-beta.6 but I'm unable to do so. Here's what I'm seeing when trying to install the package.

`PM> Install-Package Recurly -Version 3.0.0-beta.6
Restoring packages for C:\Users\Ben\Documents\GitHub\AdServerNet\AdServer\Enplug.AdServer.Billing.Recurly\Enplug.AdServer.Billing.Recurly.csproj...
  GET https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Recurly'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3-flatcontainer/recurly/index.json
  OK https://api.nuget.org/v3-flatcontainer/recurly/index.json 390ms
  OK https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Recurly'&semVerLevel=2.0.0 656ms
Install-Package : NU1102: Unable to find package Recurly with version (>= 3.0.0-beta.6)
  - Found 5 version(s) in nuget.org [ Nearest version: 3.0.0-beta.5 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Users\Ben\Documents\GitHub\AdServerNet\nuget
  - Found 0 version(s) in avalonia-nightly
At line:1 char:1
+ Install-Package Recurly -Version 3.0.0-beta.6
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Enplug.AdServer.Billing.Recurly'.
At line:1 char:1
+ Install-Package Recurly -Version 3.0.0-beta.6
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.5603508`

**Comment by BenGoldberg** [comment]
As for a stack trace, this is all I'm seeing:

```
   at Recurly.Pager`1.get_Current()
   at Enplug.AdServer.Billing.Recurly.RecurlyBillingProcessor.GetAccountSubscriptions(String accountCode) in C:\Users\Ben\Documents\GitHub\AdServerNet\AdServer\Enplug.AdServer.Billing.Recurly\RecurlyBillingProcessor.cs:line 618
```

**Comment by bhelx** [comment]
Sorry, `beta-6` is not in nuget yet. That stack trace seems pretty slim. Perhaps the package is missing pdb files or something.

Is the exception being thrown on the line:
`var pager = _client.ListAccountSubscriptions($"code-{accountCode}", state: "live");`
or one of the following lines? If so, could you provide some more code. Also, which version of dotnet are you using?

**Comment by BenGoldberg** [comment]
I am using .NET Core version 2.2.300. The exception isn't being thrown from that line, it's thrown when actually iterating the pager. So for example this will throw:

`pager.ToList()`

Also this:

`foreach (var subscription in pager)`

Should I try cloning the Recurly project and running the code myself? If the problem still exists in the latest version, I could at least get a proper stack trace that way. Or is there another way to update to beta.6?

**Comment by bhelx** [comment]
> Should I try cloning the Recurly project and running the code myself? If the problem still exists in the latest version, I could at least get a proper stack trace that way. Or is there another way to update to beta.6?

@BenGoldberg  Let me try to downgrade my version to beta.5 tomorrow and see if i can repro. If you have time to do that though, it might be helpful in the case that I still cannot repro!

**Comment by bhelx** [comment]
@BenGoldberg I had a moment now actually, was able to repro by downgrading. I believe it's related to a fix I made here: https://github.com/recurly/recurly-client-net/commit/9b0ff7b2347f75a7198bc2745632d9f61a422ea0

I'll get a release cut and push out beta-6 first thing tomorrow and link back here. Sorry for not noticing earlier!

**Comment by bhelx** [comment]
On a related note, I'm looking into publishing a symbols file `.snupkg` along with the release. I think this will make debugging easier.

**Comment by BenGoldberg** [comment]
@bhelx That's great, I'm glad the issue is already fixed in the latest version! Looking forward to the build release today, thanks for that.

**Comment by bhelx** [comment]
Should be fixed in https://github.com/recurly/recurly-client-net/releases/tag/3.0.0-beta.6

**Comment by bhelx** [comment]
@BenGoldberg let me know if that version fixes the problem for you. Keep in mind it has that one breaking change outlined in the Release Notes.

**Comment by BenGoldberg** [comment]
@bhelx I updated to beta.6 and it fixed the problem, thank you! However I have a few questions about the new version:

- The BillingInfo object has a property called PaymentMethod. In beta.5 this was a dictionary, now however it is an object. In beta.5 I was able to grab a property for checking accounts called "routing_number_bank" from the dictionary which was very useful, however in the new version I am not able to access this property. Is it possible to add it to the PaymentMethod object being returned?
- I noticed the List properties in the Create objects don't come pre-initialized. For example, for the SubscriptionCreate object, there is an AddOns property to add add ons to the request. Right now I have to create a new list and then add the SubscriptionAddOnCreate objects inside of it. Would it make sense to initialize these list properties when creating the objects so you would only have to add to them when creating the requests? I ran into a couple unexpected NPE because of this.

Let me know if there's a more appropriate channel to discuss the above points.

**Comment by bhelx** [comment]
@BenGoldberg appreciate the input. sorry about the changes, we still havent stabilized the API yet. I noticed a couple things missing from the spec including `routing_number_bank`. Ive added that in and I'm getting out another small release for you :)

**Comment by bhelx** [comment]
https://github.com/recurly/recurly-client-net/releases/tag/3.0.0-beta.7
https://www.nuget.org/packages/Recurly/3.0.0-beta.7

If you have any other problems the best thing to do is file a new issue. I'll be able to address them individually.

**Comment by bhelx** [comment]
> I noticed the List properties in the Create objects don't come pre-initialized. For example, for the SubscriptionCreate object, there is an AddOns property to add add ons to the request. Right now I have to create a new list and then add the SubscriptionAddOnCreate objects inside of it. Would it make sense to initialize these list properties when creating the objects so you would only have to add to them when creating the requests? I ran into a couple unexpected NPE because of this.

I'll look into doing this. I want to make sure i assess the possible impact. For now you'll need to initialize the lists yourself.

**Comment by BenGoldberg** [comment]
I appreciate all the help! There's one more small thing I'm running into but I will file a new issue for it.
