### ISSUE TITLE
ChangeSubscription with Addon removal doesn't update subscription addon quantity

### ISSUE THREAD

**Issue by atschaef** [recurly/recurly-client-net#47]
I noticed that whenever i want to change a subscription that had a single addon item, to one that has no addons, the subscription addon isn't updated in recurly (still get return code of 2xx).

I remove the item like so (simplified)
```
var subscription = recurly.GetSubscription(account);
subscription.AddOns.RemoveAt(0);
recurly.ChangeSubscription(subscription, Subscription.ChangeTimeframe.Renewal);
```

As a workaround, I created the xml for the request myself, and noticed that if the element "subscription_add_ons" is not present, then recurly ignores the change to the addon.  When I add this element, and instead leave the "subscription_add_on" element block(s) blank, the subscription is updated, and I see the pending subscription as i would expect.

I believe the issue lies in Subscription.cs line 581 in the WriteChangeSubscriptionXml method. (Added comment to point out line)
```
xmlWriter.WriteStartElement("subscription"); // Start: subscription
xmlWriter.WriteElementString("timeframe", timeframe.ToString().EnumNameToTransportCase());
xmlWriter.WriteElementString("quantity", Quantity.AsString());
xmlWriter.WriteStringIfValid("plan_code", _planCode);

xmlWriter.WriteIfCollectionHasAny("subscription_add_ons", AddOns); //<------This line here

xmlWriter.WriteStringIfValid("coupon_code", _couponCode);
```

When I dive down deeper into XmlWriterExtensions.cs, i noticed that the collection name is not written in the method call. (Added comment to point out lines)
```
if (!items.HasAny()) return;  //<---- return before necessary collection name block is written for addon remvoal
writer.WriteStartElement(collectionName); //<--- in this case, if we write this with its end, we get the desired results
foreach (var item in items)
{
    writer.WriteElementString(localName(item), stringValue(item));
}
writer.WriteEndElement();
```

I haven't done the research to know if any other element blocks behave this way, so this may be a bug with the recurly api, not the .net client, but for this case at least, the collection name block must exist for the change to work.

**Comment by MuffinMan10110** [comment]
@atschaef Are you still having an issue with this using the latest build? I've tested and also looked at the source code and I believe it's been fixed since this issue. I've observed using your sample code that the `subscription_add_on` xml is being written.

Here's the request that is generated using your sample code.

    <subscription>
      <timeframe>renewal</timeframe>
      <quantity>1</quantity>
      <plan_code>pc2015091501155287757</plan_code>
      <subscription_add_ons />
      <unit_amount_in_cents>1900</unit_amount_in_cents>
      <collection_method>automatic</collection_method>
    </subscription>

@bhelx Can we close this?

**Comment by bhelx** [comment]
@MuffinMan10110 sure, if we can't replicate.

@atschaef please let us know if it's not a fixed issue.
