### ISSUE TITLE
ChangeSubscription requires cost of new plan

### ISSUE THREAD

**Issue by cpt-klossome** [recurly/recurly-client-net#49]
I am not sure if this is be design or not, but when changing the subscription, the price does not update.  For example: If a user is on Plan-A that costs $15 and I use the API to change them to Plan-B which is $5, the plan updates but the price does not. I have to include the price of the new subscription in order to get it to update.

```
            var subscription = GetRecurlySubscription(Member.MemberID.ToString());
            Plan newPlan = Plans.Get(Member.PlanCode);
            if (subscription != null && newPlan != null)
            {   
                subscription.Plan = newPlan;
                subscription.UnitAmountInCents = newPlan.UnitAmountInCents.Values.FirstOrDefault();
                subscription.ChangeSubscription(Subscription.ChangeTimeframe.Now);                    
            }
```

**Comment by MuffinMan10110** [comment]
@cpt-klossome Thanks for providing a code sample. In this example you are right, calling the `ChangeSubscription` method will not update your `subscription` variable with updated data. You would need to fetch the subscription again to see the latest changes.

**Comment by bhelx** [comment]
@cpt-klossome were you able to figure this out?

**Comment by 1TheMuffinMan** [comment]
@cpt-klossome Please let us know if you are still encountering issues with the `ChangeSubscription` endpoint and we'll be happy to assist. Closing for now.
