### ISSUE TITLE
Unable to add description when submitting a one-off transation

### ISSUE THREAD

**Issue by geekexplorer** [recurly/recurly-client-net#57]
While the  general API documentation mentions you can pass in a 'description' when submitting a new one-off transaction, the .Net Recurly-Api-Client v. 1.1.6.0 doesn't allow you to do so.  Neither of the two provided constructors support including a description.  Further, it doesn't appear that there is a public description field on the class so I am unable to add it after initialization either.

The documentation I’m referring to can be found here:  https://docs.recurly.com/api/transactions under “Create transaction.”

**Comment by cgerrior** [comment]
Hi @geekexplorer,

Please see https://github.com/recurly/recurly-client-net/pull/90.

**Comment by bhelx** [comment]
This should have been taken care of by https://github.com/recurly/recurly-client-net/pull/90
