### ISSUE TITLE
Constants.PaymentMethod missing Braintree

### ISSUE THREAD

**Issue by bgilbert6** [recurly/recurly-client-net#643]
**Describe the bug**

When deserializing JSON output from Recurly, braintree ends up "Undefined", because it isn't in Constants.cs.

**To Reproduce**

Call GET BillingInfo with a billing info backed by braintree. The braintree payment_method is: `object=braintree_v_zero`

You can see this isn't included in Constants.PaymentMethod:
```


public enum PaymentMethod        
{            
            Undefined = 0,
            [EnumMember(Value = "amazon")]            Amazon,
            [EnumMember(Value = "amazon_billing_agreement")]            AmazonBillingAgreement,
            [EnumMember(Value = "apple_pay")]            ApplePay,
            [EnumMember(Value = "bank_account_info")]            BankAccountInfo,
            [EnumMember(Value = "check")]            Check,
            [EnumMember(Value = "credit_card")]            CreditCard,
            [EnumMember(Value = "eft")]            Eft,
            [EnumMember(Value = "gateway_token")]            GatewayToken,
            [EnumMember(Value = "iban_bank_account")]            IbanBankAccount,
            [EnumMember(Value = "money_order")]            MoneyOrder,
            [EnumMember(Value = "other")]            Other,
            [EnumMember(Value = "paypal")]            Paypal,
            [EnumMember(Value = "paypal_billing_agreement")]            PaypalBillingAgreement,
            [EnumMember(Value = "roku")]            Roku,
            [EnumMember(Value = "sepadirectdebit")]            Sepadirectdebit,
            [EnumMember(Value = "wire_transfer")]            WireTransfer,
};

```

**Expected behavior**

Braintree should map to a `Braintree` payment method

**Your Environment**

- Which version of this library are you using? The lastest dotnet
- Which version of the language are you using? .NET Core 3.1

**Comment by douglasmiller** [comment]
@bgilbert6, I am sorry that it has taken us so long to address this issue. We will have the `BraintreeVZero` enum added soon. We will update you when it has been released.

**Comment by rer7891** [comment]
@bgilbert6 I'm happy to report that the `BraintreeVZero` enum has been updated and released. Please let us know if you have any additional issues.
