### ISSUE TITLE
Invoices are broken - API calls using this project are crashing getting invoices

### ISSUE THREAD

**Issue by AdamYEG** [recurly/recurly-client-net#68]
The XML doc being parsed has two elements of "state".

one state is under address and the other one is for the invoice.

The StringExtensions.cs code is crashing on:
 public static T ParseAsEnum<T>(this string source) 
        {
            var sanitized = source.ToPascalCase();
            if (sanitized.IsNullOrEmpty())
                throw new ArgumentException("Cannot convert a null or empty string to an Enumeration.", "source");

            return (T)Enum.Parse(typeof(T), sanitized, true);
        }

because it's being passed the address state before the invoice state.

This is from Invoice.cs

internal override void ReadXml(XmlTextReader reader)
        {
            while (reader.Read())
            {
                // End of invoice element, get out of here
                if (reader.Name == "invoice" && reader.NodeType == XmlNodeType.EndElement)
                    break;

                if (reader.NodeType != XmlNodeType.Element) continue;

                switch (reader.Name)
                {
                    case "account":
                        var accountHref = reader.GetAttribute("href");
                        AccountCode = Uri.UnescapeDataString(accountHref.Substring(accountHref.LastIndexOf("/") + 1));
                        break;

                    case "subscription":
                        var subHref = reader.GetAttribute("href");
                        SubscriptionUuid = Uri.UnescapeDataString(subHref.Substring(subHref.LastIndexOf("/") + 1));
                        break;

                    case "uuid":
                        Uuid = reader.ReadElementContentAsString();
                        break;

                    case "state":
                        State = reader.ReadElementContentAsString().ParseAsEnum<InvoiceState>();
                        break;

                    case "invoice_number":
                        int invNumber;
                        if (Int32.TryParse(reader.ReadElementContentAsString(), out invNumber))
                            InvoiceNumber = invNumber;
                        break;

                    case "po_number":
                        PoNumber = reader.ReadElementContentAsString();
                        break;

                    case "vat_number":
                        VatNumber = reader.ReadElementContentAsString();
                        break;

                    case "subtotal_in_cents":
                        SubtotalInCents = reader.ReadElementContentAsInt();
                        break;

                    case "tax_in_cents":
                        TaxInCents = reader.ReadElementContentAsInt();
                        break;

                    case "total_in_cents":
                        TotalInCents = reader.ReadElementContentAsInt();
                        break;

                    case "currency":
                        Currency = reader.ReadElementContentAsString();
                        break;

                    case "created_at":
                        DateTime createdAt;
                        if (DateTime.TryParse(reader.ReadElementContentAsString(), out createdAt))
                            CreatedAt = createdAt;
                        break;

                    case "closed_at":
                        DateTime closedAt;
                        if (DateTime.TryParse(reader.ReadElementContentAsString(), out closedAt))
                            ClosedAt = closedAt;
                        break;

                    case "tax_type":
                        TaxType = reader.ReadElementContentAsString();
                        break;

                    case "tax_rate":
                        TaxRate = reader.ReadElementContentAsDecimal();
                        break;

                    case "net_terms":
                        NetTerms = reader.ReadElementContentAsInt();
                        break;

                    case "collection_method":
                        CollectionMethod = reader.ReadElementContentAsString();
                        break;

                    case "line_items":
                        // overrite existing value with the Recurly API response
                        Adjustments = new AdjustmentList();
                        Adjustments.ReadXml(reader);
                        break;

                    case "transactions":
                        // overrite existing value with the Recurly API response
                        Transactions = new TransactionList();
                        Transactions.ReadXml(reader);
                        break;
                }
            }
        }

As of right now - getting any invoices does not seem to work.

**Comment by austinheap** [comment]
Hi @AdamYEG, thank you for reporting to this. We are looking into it internally.

**Comment by austinheap** [comment]
Hi @AdamYEG, this was fixed in a previous release. The code that fixed this is here:

https://github.com/recurly/recurly-client-net/blob/master/Library/Invoice.cs#L258-L260

Can you please let me know what version you're using? Thank you.

**Comment by AdamYEG** [comment]
Thanks for quick reply.

I'm using dll ver 1.1.7.0 on a project running .net 4.5.

I just grabbed latest dll today from :

https://github.com/recurly/recurly-client-net/releases/tag/1.1.7

**Comment by austinheap** [comment]
@AdamYEG Thanks for the update -- did that fix the issue for you?

**Comment by AdamYEG** [comment]
Hi Austin,

I cloned the current project - and I see the fix and appears to work.

Before that - I was using the last "Stable" release on the release page (
https://github.com/recurly/recurly-client-net/releases/tag/1.1.7) <-- Does
not have the fix yet....?

That was the issue.  When does the current code get promoted to a stable
release package?

Thanks,

Adam

**Comment by drgrieve** [comment]
I had the same issue with 1.1.0 

I updated nuget package to 1.1.8 and the issue has been fixed.

**Comment by cbarton** [comment]
closing since the issue has been reported as fixed.
