### ISSUE TITLE
Customer notes support for invoices missing?

### ISSUE THREAD

**Issue by mms-** [recurly/recurly-client-net#71]
This doesn't seem to be apart of this lib yet, any idea when?

**Comment by austinheap** [comment]
Hi @mms-, we're working on this and it'll be available in the upcoming weeks.

**Comment by cbarton** [comment]
This is to be handled by https://github.com/recurly/recurly-client-net/pull/67

**Comment by cbarton** [comment]
@mms- sorry about the **long** delay. This has been released under v1.1.9

Let us know if there are any other issues!
