### ISSUE TITLE
Update billing info with token not working

### ISSUE THREAD

**Issue by drgrieve** [recurly/recurly-client-net#73]
code

           var account = Accounts.Get(AccountId);
           var info = account.BillingInfo;
            if (!String.IsNullOrEmpty(model.RecurlyToken))
            {
                info.TokenId = model.RecurlyToken;
                info.Update();
            }

But in the Xml sent, it is sending all of the billing info not just the token

<?xml version="1.0" encoding="utf-8"?>
<billing_info>
  <first_name>Simon</first_name>
  <last_name>Simple</last_name>
  <address1>Test</address1>
  <city>Crows Nest</city>
  <state>NSW</state>
  <zip>1585</zip>
  <country>AU</country>
  <ip_address>203.206.181.135</ip_address>
  <token_id>YxhDoZU2mv89UalVwmEJRg</token_id>
</billing_info>

Error response (not handled BTW throws exception)

<?xml version="1.0" encoding="UTF-8"?>
<error>
  <symbol>billing_info_invalid</symbol>
  <description>no other attributes are allowed when a token is provided</description>
</error>

**Comment by drgrieve** [comment]
A workaround for this.

                var account = Accounts.Get(AccountId);
                if (!String.IsNullOrEmpty(model.RecurlyToken))
                {
                    account.BillingInfo = new BillingInfo(account) { TokenId = model.RecurlyToken };
                    account.BillingInfo.Update();
                }

WriteXml method should check for token and if present only write that field.

**Comment by drewish** [comment]
Yeah you're correct it should be token or billing info. Thanks for bringing it to our attention.

**Comment by austinheap** [comment]
Hi @drgrieve, thanks for letting us know. We're looking into it.
