### ISSUE TITLE
Changing Private Api Key at Runtime

### ISSUE THREAD

**Issue by pburrows** [recurly/recurly-client-net#77]
The private apiKey for recurly is defined in a configuration section. If you use two different recurly accounts (one for production, and one for testing -- which is how recurly recommends you set up testing), you are not able to make a decision at run time about which key / account to use.

Need to add a feature to allow the private api key to be modified at run time.

**Comment by MuffinMan10110** [comment]
This sounds like it could be avoided by modifying your deployment strategy. With any .NET app in general there is no runtime changes to configuration, you build in debug or release and deploy that version. If you happen to have test servers then you probably have a deployment manager such as Octopus Deploy and you change web.config variables before you deploy to a specific environment.

Maybe you can provide more information on why you would want to do this at runtime vs. compile or deployment time?

**Comment by pburrows** [comment]
Sure, this could be modified by an external service. It could even be edited by hand. It would be nice to also allow it to be edited at runtime for people who are not using those features (or would prefer not to keep it in a .config file at all).

**Comment by MuffinMan10110** [comment]
Hey @pburrows  I understand where you're coming from, but I think what you're requesting goes against best practices and you're probably going to need to perform this work on your own fork. If you'd like to attempt it yourself I can give you some tips on how to accomplish it:

1. There is no public object to set the credentials, the internal class grabs the section from the app/web.config and stores it in a singleton object. You'll need to make the Settings class public or find some place to create a method that updates the credentials
2. Choose to continue to use the app/web.config as a persistence store or just update the singleton object through your new method.

Again I think this is a terrible idea as your app shouldn't be multi environment aware, but to each their own :).

**Comment by bhelx** [comment]
@pburrows Is this still a problem for you? Do you have an implementation in mind?

**Comment by pburrows** [comment]
I haven't had the time to code up anything more fancy. For the moment I am just trying to remember to comment / uncomment individual lines in the web.config file. Most of the environment changes I do are based on settings either in Octopus Deploy or in the AppSettings for an Azure Web Site instance. But since this config entry isn't part of AppSettings and is something custom, I would have to do something different here. And I just haven't had time.

**Comment by MuffinMan10110** [comment]
Patrick,

I also use Octopus Deploy and change the private API key between each environment I deploy to. I build once and change config settings when deploying. In your post deploy step add the following Powershell code:

    $filePath = $OctopusParameters['Octopus.Action[Web Portal].Package.CustomInstallationDirectory'] += "\Web.config"

    [xml] $xml = Get-Content $filePath

    $recurly = $xml.SelectSingleNode('/configuration/recurly')
    $recurly.apiKey = $OctopusParameters['Recurly.ApiKey']
    $recurly.subdomain = $OctopusParameters['Recurly.SubDomain']

    $xml.Save($filePath)

This is necessary because recurly is a custom section in the webconfig, not an appkey. Also note that you'll need to add apikey and subdomain as variables in your process. I used "Recurly.ApiKey" and "Recurly.SubDomain" as mine.

**Comment by pburrows** [comment]
Hey, cool. Thanks for the snippet.

**Comment by bhelx** [comment]
Thanks @MuffinMan10110 !

I'm going to go ahead and close this for now. I'm certainly open to re-open and talk about an implementation if you feel like it hasn't been fixed for you @pburrows . Just re-open if you want to continue.

**Comment by MuffinMan10110** [comment]
@pburrows If you need any help with Octopus just shoot me an email (it's in my profile), I'd be glad to help.
