### ISSUE TITLE
Connection times out to Recurly api server on Recurly.Plans.List()

### ISSUE THREAD

**Issue by mms-** [recurly/recurly-client-net#82]
Every 2-3 hours I get the following in my logs, looks like Recurly api server is failing?

It's always on the  Recurly.Plans.List() function. Perhaps that just because we call this API the most. Seen these for months now, and it re-occurs every few weeks or so. Is it the library or the server/api?

System.Net.Sockets.SocketException: A connection attempt failed because the 

connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 64.74.141.63:443 at 

System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, 

Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at 

System.Net.HttpWebRequest.GetResponse() at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, WriteXmlDelegate writeXmlDelegate, ReadXmlDelegate readXmlDelegate, 

ReadXmlListDelegate readXmlListDelegate) at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, ReadXmlListDelegate readXmlListDelegate) at 

Recurly.RecurlyList`1.GetItems() at Recurly.Plans.List()

**Comment by bhelx** [comment]
Thanks @mms-

I'm going to take a look at this today.

**Comment by bhelx** [comment]
@mms- 

My first guess is it's a network related issue and not the code, but these types of intermittent network issues are really hard to diagnose. A couple questions:

+ Could you provide a rough estimate for datetime range that this is happening? Is it still happening?
+ Is this happening locally, on your server, or both?
+ Was it working fine before or have you been seeing this since beginning to use the library?

**Comment by mms-** [comment]
It's only been seen in the datacenter, (Azure West US, the only place I have this deployed). I don't really run the library locally so I can't say.

It may be an issue that becomes visible only during high network load, however I would expect other connection failures as well, so far the Recurly server is the only one.

It has been occurring for some months, Every few days a burst of these errors will come in, at times a few an hour for 24 hours. Most recent timestamps are : 
2015-05-14 15:32:33
2015-05-14 15:11:59
2015-05-14 12:13:34
2015-05-14 12:13:11
2015-05-14 11:42:40
These are UTC -08:00. One thing that is odd is the same server failed very close together 12:13:34 and 12:13:11, so it would seem that during that time even retry attempts fail.

I'd say it's been occurring since the beginning of the library, though I can't be sure.

I provided Recurly support with specific timestamps when this occurred however they couldn't match it to anything in their servers.

Is it possible that Recurly.Plans.List() is a heavy payload function and a bit too sensitive to network conditions? Is the network timeout specifically set by the recurly-client-net library?

Is there a throttle limit on Recurly apis? Right now I would say I call this api once every 5 min as that is the refresh timer on the cache.

I will run some tests for period of time on a separate server to make sure it's not the webroles causing this.

**Comment by MuffinMan10110** [comment]
I believe there is a rate limit on Recurly API calls. If you look at the
response headers you should see your current usage, quota and a timestamp
of when it resets.

**Comment by bhelx** [comment]
@mms- @MuffinMan10110 yes there is a rate limit on calls:

https://docs.recurly.com/api/basics/rate-limits

However, they happen at the HTTP level. Not the TCP level. So if you were hitting a rate limit you would still be connecting to our server and receiving an HTTP 429 status code. But it seems to me like @mms- is failing to connect at the TCP level.

There is a timeout defined in the library:

https://github.com/recurly/recurly-client-net/blob/ef397a2813a8113cab4eb02dfcc4c2807d2e07e5/Library/Client.cs#L134

but it appears it is only set for POST and PUT requests. You could maybe try to modify the library at that point and move the timeout up to apply to GET requests as well (I believe the Plans.List() call is a GET). You'd just move that line to right above this conditional check:

https://github.com/recurly/recurly-client-net/blob/ef397a2813a8113cab4eb02dfcc4c2807d2e07e5/Library/Client.cs#L131

I would also make an attempt to replicate this on another network (perhaps make a lot of fast simultaneous calls from your local system?). It could be that your issue is at the Azure level. I am asking our operations and networking team if they have any ideas and I'll report back here.

**Comment by mms-** [comment]
Yes I don't think I'm reaching any api call limits, though I haven't checked what the headers say.

I will look into this more, try your suggestions and report back as soon as I get some time.

What is peculiar is that I've only seen this with the plans list api call, but that must be because it's called much more than the other api calls. A simple test would be to run a backround task that makes random get calls to Recurly every minute or so, this should surface any issues.

**Comment by bhelx** [comment]
@mms- any updates? I'm closing for now. Feel free to re-open if you still think it's a problem.

**Comment by mms-** [comment]
Hello, haven't seen this since Feb 24, 2016. However recently about a week ago am seeing this every few hours: 

System.Net.WebException: The remote server returned an error: (522) Origin Connection Time-out.
 at System.Net.HttpWebRequest.GetResponse()
 at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, WriteXmlDelegate writeXmlDelegate, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate reseponseDelegate)
 at Recurly.Subscription.get_Plan()

As you can see this comes from the Subscription.Plan property. The other place where I'm seeing this is in Recurly.Accounts.Get(id) calls.

If it helps the last time this occurred was just after 2016-05-19 22-26-56 UTC on the Subscription.Plan getter.

Status code 522 suggests some sort of timeout, is this something Recurly servers return?

Have never seen a 429 Too Many Requests as I would if this was a rate issue.
Again this is in Azure West US data center.

**Comment by MuffinMan10110** [comment]
A quick Google search yielded that http 522 is used by cloudfare. I'm assuming the way things are set up is that client requests are proxied and then that proxy tries to establish a connection to the actual endpoint but that endpoint didn't respond. If that is true it sounds more like the infrastructure is taxed than a code problem.

**Comment by mms-** [comment]
Yes I found that as well, not sure where CloudFlare fits in, must be somehow in the middle!

Adding a retry strategy makes sense here, as it is common and desirable to handle infrastructure failures like this at the API/SDK level where possible: https://azure.microsoft.com/en-us/documentation/articles/best-practices-retry-service-specific

Also because properties such as subscription.Plan actually make a network call, inserting your own retry logic would be very messy with this API. Usually you don't want property getters making network calls on an APIs.

**Comment by bhelx** [comment]
@mms- Yes, I believe this is coming from Cloudflare this time. Do you have a list of the datetimes in which this occurred?

**Comment by mms-** [comment]
Around:
2016-05-19 22-26-56 UTC
2016-05-18 22-18-51 UTC
2016-05-17 22:11:33 UTC
2016-05-13 09-44-13 UTC

Mostly 22:00 as that is when our billing task runs. Does Recurly use CloudFlare explicitly? Azure does not so it's not on my end I believe.

**Comment by bhelx** [comment]
@mms- Yes, we do now. I know we had a few hiccups last Thursday with Cloudflare but I'll have to check with our team about these other dates. Is this an intermittent problem? Does it happen every once in a while or for batches of requests? Do you have an idea of the throughput of the requests at that time? Any information would be helpful.

**Comment by mms-** [comment]
Seems to happen every other time in the middle of a batch. We have < 100 accounts so the rate of query can't be that high.. get account, get subscription get plan, that's it. It fails for one account, we then continue on with the next account and these succeed. No rate errors from Recurly itself.

**Comment by mms-** [comment]
Again, twice today, once in each batch..

**Comment by bhelx** [comment]
@mms- I'd recommend contacting support as they have processes to help identify these types of networking issues.

**Comment by mms-** [comment]
Will do if it persists. Any desire to add retry to the lib?

**Comment by MuffinMan10110** [comment]
@mms- I think any error handling or retry logic would be most appropriate in the consuming application. That being said though, I would happy to help come up with a retry sample if you'd like.
