### ISSUE TITLE
Subscription Constructor is missing bulk flag

### ISSUE THREAD

**Issue by jcwrequests** [recurly/recurly-client-net#88]
The Subscription Constructor is missing the bulk flag as an option. Is there any plans to get this added or would you need a PR?

**Comment by cgerrior** [comment]
Hi @jcwrequests, please see https://github.com/recurly/recurly-client-net/pull/89.

**Comment by jcwrequests** [comment]
@cgerriir thanks

**Comment by cbarton** [comment]
merged
