### ISSUE TITLE
Subscription Preview method is broken

### ISSUE THREAD

**Issue by MuffinMan10110** [recurly/recurly-client-net#95]
The Recurly API endpoint PreviewSubscription now returns a child node for invoice which the ReadXml method in Subscription.cs is not set up to handle.

https://github.com/recurly/recurly-client-net/blob/cfff76bbaf35ccfbf7cfe741c0136063e868ec38/Library/Subscription.cs#L427

What's happening is this switch case is correctly reading the State element from the subscription XML, but then the reader starts to traverse the invoice and sees a State element there as well. The issue is that the code is trying to parse the enum for the invoice state which isn't in the SubscriptionType enum.

I believe all that needs to be done is to check for the existence of the invoice and call out to Invoice.cs to read the xml.

**Comment by bhelx** [comment]
Thanks for the detailed post @MuffinMan10110 

A PR would be great!

**Comment by bhelx** [comment]
@MuffinMan10110 I'm planning on taking a look at this tonight to see if I can get a patch. Did you start on anything for it?

**Comment by MuffinMan10110** [comment]
@bhelx Thanks for following up. I've fixed the client library so it stops breaking in my own local version, but ideally the client library conforms to the new xml schema that is coming back from the API. I need to know if the API endpoint is set in stone or if it might continue to evolve. I see there is a Beta tag in the docs which is why I ask.

**Comment by bhelx** [comment]
Yes, unfortunately the API is already set. But, if your branch fixes the issue that would be good enough for now. I can do a follow up issue to see how we can do a better job of solving it.

**Comment by MuffinMan10110** [comment]
If the API is set then that is good news. I will submit a pull request asap.

**Comment by bhelx** [comment]
Thanks @MuffinMan10110 !

**Comment by MuffinMan10110** [comment]
@bhelx I just submitted a pull request for this
